### ISSUE TITLE
Write percentile component

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#147]
Write a TECA algorithm to transform an input 2D field into field-relative percentiles (ranging from 0 to 1).

See #146

**Comment by burlen** [comment]
An indirect sort is likely the approach, as input values need not be shuffled, we only need to know the correct ordering and where to store the result.

@taobrienlbl  Should the output field be discrete (eg 100 integer values) or continuous (floating point)?

**Comment by taobrienlbl** [comment]
This sounds right to me.  Let's go with floating point: 0 to 1
