### ISSUE TITLE
driver for probabilistic ar detector

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#150]
need to write a driver for the new ar pipeline. this will generate the requests for each of P (percentile), A (area threshold), and dy (std deviation of the Gaussian)

How does the averaging fit into this?
The parameter set is order 1000.

How does this fit into the map reduce over time steps?

see mr #146

**Comment by burlen** [comment]
@taobrienlbl can you upload a parameter file?

**Comment by taobrienlbl** [comment]
Here is a small file with 128 samples (zipped b/c github wouldn't let me upload the raw netcdf file itself).  I can generate a larger one later if needed for performance testing.  The file format can be flexible too.

[ar_detector_parameters.nc.zip](https://github.com/LBL-EESA/TECA/files/2857597/ar_detector_parameters.nc.zip)

**Comment by burlen** [comment]
the parameter file converted to teca table
[parms.tar.gz](https://github.com/LBL-EESA/TECA/files/2979958/parms.tar.gz)
