### ISSUE TITLE
Write area filter component

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#152]
This might be trivial.

This should remove connected components with areas that are too small.  Currently, the connected-component algorithm in TECA outputs a 2D array w/ a unique ID for each connected component (and each cell w/in a component gets assigned that ID).  If the area-of-components step (see #149) returns an array where component IDs are replaced with the area of each component, then this step could possibly just be the 'segment' operation, with the threshold being the minimum area.

See #146

**Comment by burlen** [comment]
see `test_2d_component_area` for an example of accessing component labels and their corresponding areas.

**Comment by burlen** [comment]
merged
