### ISSUE TITLE
use latest linux (ubuntu or fedora) image w/ travis ci

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#165]
1. make use of Abdel's recent work on setting docker images up to configure an image for Travis CI
2. set our travis ci linux build to use it

**Comment by elbashandy** [comment]
Please send me our Travis CI info and access

**Comment by burlen** [comment]
I believe (but could be wrong) that there is no travis ci accounts. it's all via github. and also you don't need to do anything in either github or travis. that part has been set up for quite some time. take a look at the yaml files in the repo.

also see this
https://docs.travis-ci.com/user/docker/

let me know if I'm missing something

**Comment by burlen** [comment]
also setup Python 3 environment, see #205

**Comment by burlen** [comment]
this is getting to be a higher priority, the following looks like a compiler bug in the versions used with 14.04. http://cdash.hpcvis.com/viewBuildError.php?buildid=4009

**Comment by elbashandy** [comment]
Done
