### ISSUE TITLE
teca_cf_reader not dealing with MERRA data

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#174]
It looks like `teca_cf_reader` cannot deal with MERRA files (e.g., files in this regex pattern at nersc `/project/projectdirs/m1517/cascade/external_datasets/ARTMIP/MERRA\ 2D/2017/ARTMIP_MERRA_2D_2017021[456]*`).

I suspect the issue is that the files have no time dimension... :/

> ```Failed to read metadata for variable "time" from "ARTMIP_MERRA_2D_20170214_00.nc". NetCDF: Invalid dimension ID or name```

As unfortunate as this non-standard format is, this is critical for the probabilistic AR detector, since all algorithms in the ARTMIP project must run their algorithms on these files.  The time is encoded in the filename (why not take advantage of the metadata within the file, I don't know...), so perhaps an alternate netCDF reader is needed that can decode time information from a filename given some sort of parseable coding pattern like "ARTMIP_MERRA_2D_YYYYMMDD_HH.nc"

**Comment by burlen** [comment]
the cf reader can handle datasets without a time axis. By default we expect a time axis, so you'd need to call 
```
r->set_t_axis_variable("");
```
or the equivalent in Python. The command line tools have command line arguments to do it as well. You may need to use the `--full_help` to see them.

**Comment by burlen** [comment]
note: when there is no time axis, the reader uses the regex to determine the order of the files.

**Comment by taobrienlbl** [comment]
Got it, that works: thanks.

**Comment by burlen** [comment]
That's great that it works!

When there's no time axis, the cf reader uses an integer value based on the order the files come out of the regex. I could see issues with that approach, for instance detectors that have a duration criteria. 

It would not be too bad to build a new reader either derived from or forwarding to the cf_reader to pull time out of the file name. One idea is make the user provide a calendar string and a string based template eg `YYYYMMDD_HH` that we could parse to figure the positions of the various info.

If that's needed, please re-open this issue.

**Comment by taobrienlbl** [comment]
Good point, and will do if it seems that we need this capability.
