### ISSUE TITLE
implement test/python/test_latitude_damper.py

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#176]
It looks like there is no unit test for python API of `teca_latitude_damper.cxx`.  Could I please request that one be created?   I would suggest that this be implemented as `test/python/test_latitude_damper.py`.

**Comment by taobrienlbl** [comment]
I think the core code would look something like the following, which is working for me in jupyter (nice!):

```python
import teca

filter_alg = teca.teca_latitude_damper.New()
filter_alg.set_input_connection(cfr.get_output_port())
filter_alg.set_center(0.0)
filter_alg.set_half_width_at_half_max(30.0)
filter_alg.set_damped_variables(['IVT'])
```

**Comment by burlen** [comment]
@elbashandy is it ok if you take this one?

**Comment by elbashandy** [comment]
Sure no problem.
