### ISSUE TITLE
ability to input a list of files to the cfreader (and date info)

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#185]
Following a 3/26/19 zoom call, @burlen  and @taobrienlbl agreed that it could be useful if the CF reader could accept something like a vector of filenames as input.  The fallback (I think) would be the regex functionality that exists now.

This is related to #183, where the files over which TECA will loop are a random list of files.  The order of the filenames is important here, since each file corresponds to a count of ARs within that image (which were hand-counted by members of the CASCADE team).  The TECA pipeline that I'll construct for this will ultimately do a reduction that returns a list of the number of ARs that TECA counts within each file; the order of these counts needs to correspond to the order of the counts in the human-count dataset.

For certain types of files (e.g., the MERRA2 ARTMIP dataset - see #177), the time information is not contained. In this case, it could also be useful if the cfreader also accepts udunit-compatible time input (e.g., a vector of 'days since 1979-01-01 00:00:00' values, along with an input string describing the time units of 'days since...').

**Comment by burlen** [comment]
@elbashandy Let's meet up next week and discuss what the solution looks like

**Comment by burlen** [comment]
this is 2 features
1. use a vector of file names instead of a single file name
2. add a vector of double for time axis
  a. add calendar and units string, that is used if the time axis is provided.

**Comment by taobrienlbl** [comment]
See also #177

**Comment by elbashandy** [comment]
@burlen This feature was added but I remember we decided to leave this open for a reason. Should I close it?

**Comment by burlen** [comment]
we need to support multiple directories

**Comment by burlen** [comment]
close this, support for multiple directories is in #294
