### ISSUE TITLE
regression tests for applications

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#197]
make regression tests that exercise the applications in the apps dir. for now it is enough that these run without error. leave to the future a way to validate the output.

```
teca_convert_table.py
teca_dataset_metadata.py
teca_event_filter.py
teca_metadata_probe.cpp
teca_tc_detect.cpp
teca_tc_stats.py
teca_tc_storm_size.cpp
teca_tc_trajectory.cpp
teca_tc_trajectory_scalars.py
teca_tc_wind_radii.cpp
teca_tc_wind_radii_stats.py
```

**Comment by taobrienlbl** [comment]
Let's focus on just getting a test for the probabilistic AR detector for this milestone.

**Comment by burlen** [comment]
@elbashandy @taobrienlbl this issue is a very high priority. Changes in the cf writer breaking applications but there are no tests to determine what's broken. If you guys agree I'd like this issue to take precedence over other pending tasks on Abdel's queue.

**Comment by burlen** [comment]
@elbashandy another option is that I take this on. I put a meeting on the calendar this morning to figure it out.

**Comment by burlen** [comment]
@taobrienlbl would you please point me to 30 days of data containing ars?  I want to use this as the basis for a test dataset for the ar app regression tests. I poked around on m1517 project dir but some of the data I found had broken symlinks.

**Comment by burlen** [comment]
these tests don't need baselines, but we want to ensure that they run without error on some representative data

**Comment by elbashandy** [comment]
@burlen /global/cscratch1/sd/taobrien/merra_2d

**Comment by taobrienlbl** [comment]
@burlen - I would use these --`/global/cscratch1/sd/mwehner/machine_learning_climate_data/All-Hist/CAM5-1-0.25degree_All-Hist_est1_v3_run1/IVT/`.  I've run TECA BARD and the TECA pytorch algorithm successfully on both, and both produce reasonable results.

@elbashandy - the files you are referring to probably got purged.  I can redownload if you need.

**Comment by burlen** [comment]
see also #256

**Comment by elbashandy** [comment]
@taobrienlbl I am looking into this issue, do you have ready commands for each application (or the ones that you regularly use)? I guess we can talk about having pretty small datasets to run the apps on.

**Comment by burlen** [comment]
@elbashandy please see the user's guide for documentation of how to run the command line apps.. The Bayesian ar detector may not yet be documented there yet,  but should run on the same command that you run your ar detector.

**Comment by burlen** [comment]
#366 fixes 4 bugs that could have been prevented if we had app tests

**Comment by elbashandy** [comment]
@burlen It's a work in progress that I started this week.

**Comment by elbashandy** [comment]
Copying comment from PR #372 

app mpi tests are failing only with the serial builds. They're failing when an output file share more than >1 rank trying to write to it. 

I checked the collective test that we already have `test_cf_writer_collective_mpi`, and it is passing normally because it has only 1 rank per output file.

I think a flag like `TECA_HAS_NETCDF_MPI` should be passed to these tests.

`test_cf_writer_collective_mpi` output:
```
start_time_step = 0
end_time_step = -1
n_time_steps = 512
n_time_steps_per_file = 128
n_files = 4
n_ranks = 4
rank	first_time_step	last_time_step
0	0	127
1	128	255
2	256	383
3	384	511
file	ranks
0	0, 
1	1, 
2	2, 
3	3, 
running the test...
STATUS: [0:139928762396928] [/project/TECA/io/teca_cf_reader.cxx:405 TECA-BARD-v1.0.1-34-g2052a46]
STATUS: Found metadata cache ".//556d19f55f71b626b566e4554c4c1694e339c3a4.tmd"
[0:139928762396928] teca_index_executive::initialize index_initializer_key=number_of_tests number_of_tests=1 index_request_key=test_id first=213 last=213 stride=1 block_start=213 block_size=1
[0:139928762396928] teca_index_executive::get_next_request test_id=213 extent=0, 127, 0, 127, 0, 0
STATUS: [0:139928762396928] [/project/TECA/test/test_cf_writer_collective.cpp:313 TECA-BARD-v1.0.1-34-g2052a46]
STATUS: print_info_arrays::execute t=2.61902, s=213, counts=(6200, 10184), z_threshold=0.5
```

Failed tests error (`test_temporal_reduction_app_monthly_average_mpi_thread` for e.g):
```
STATUS: [1:140466323400384] [/project/TECA/io/teca_cf_reader.cxx:405 TECA-BARD-v1.0.1-34-g2052a46]
107: STATUS: Found metadata cache "/project/TECA_data/531897a606164b9e34d4ad229189feba841fd5eb.tmd"
107: start_time_step = 0
107: end_time_step = -1
107: n_time_steps = 12
107: n_time_steps_per_file = 7
107: n_files = 2
107: n_ranks = 2ERROR: 
107: rank	first_time_step	last_time_step
107: 0	0	5[1:140466323400384]
107: 1	6	11
107: file	ranks
107: 0	0, 1, 
107: 1	1, 
107:  [/project/TECA/io/teca_netcdf_util.cxx:164 TECA-BARD-v1.0.1-34-g2052a46]
107: ERROR: Collective I/O attempted with a non-MPI NetCDF install. Re-install the NetCDF C library with --enable-parallel-4. See also the output of "nc-config --has-parallel" and/or the value of the "NC-4 Parallel Support" field in the file "<prefix>/lib/libnetcdf.settings" to determine if the install supports parallel I/O.ERROR: [0:140428588521152] [/project/TECA/io/teca_netcdf_util.cxx:164 TECA-BARD-v1.0.1-34-g2052a46]
107: ERROR: Collective I/O attempted with a non-MPI NetCDF install. Re-install the NetCDF C library with --enable-parallel-4. See also the output of "nc-config --has-parallel" and/or the value of the "NC-4 Parallel Support" field in the file "<prefix>/lib/libnetcdf.settings" to determine if the install supports parallel I/O.
107: ERROR: [0:140428588521152] [/project/TECA/io/teca_cf_layout_manager.cxx:96 TECA-BARD-v1.0.1-34-g2052a46]
107: ERROR: failed to create file "prw_monthly_average_%t%.nc"
107: ERROR: [0:140428588521152] [/project/TECA/io/teca_cf_writer.cxx:282 TECA-BARD-v1.0.1-34-g2052a46]
107: ERROR: Failed to create file 0
107: testing on 2 ranksn_threads=2
```

**Comment by burlen** [comment]
why would you expect a test of parallel netcdf test to pass when using a serial build of netcdf? It can't possibly work. do the same thing that we do in the regression tests - run the collective I/O tests when there is a parallel netcdf.

**Comment by elbashandy** [comment]
@burlen did that with passing `TECA_HAS_NETCDF_MPI` to these tests. The PR is ready for review.

**Comment by burlen** [comment]
if the tests are erroring out it is not ready for a review.

**Comment by elbashandy** [comment]
They are passing :) PR #372

**Comment by burlen** [comment]
ok... I find the above comment confusing. it says you are having a problem, but in reality you are not. I'll give a review once cdash is working again.
