### ISSUE TITLE
component areas negative when lat coordinate is reversed

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#210]
When the latitude coordinate is reversed (going from +90 to -90, which is common in reanalyses), the component areas are negative.  The fix appears to be easy: adding `abs()` around the area in the summation.  I'll put in a PR on this momentarily.

@burlen and @elbashandy : I wonder if the test suite should include tests that all algorithms yield good results if latitude coordinates are reversed.

**Comment by burlen** [comment]
the issue of reversed coordinates was solved in the wang etc branch. I'll make sure this gets merged as reversed coordinate axes order break many/most/all of other algorithms.

**Comment by burlen** [comment]
see e819ff67

**Comment by burlen** [comment]
fixed
