### ISSUE TITLE
CF Writer for probabilistic AR detector

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#212]
The probabilistic AR detector would benefit from an ability to write to netCDF.  In a current iteration, [I've implemented this in python](https://bitbucket.org/lbl-cascade/teca_bayesian_ar_detector/src/master/TECANCWriter.py), using `xarray`, but this probably isn't great for performance.   This would also be a prerequisite to a stand-alone executable.

An example header for such a file follows:

```
netcdf teca_ar_detect_time_1900-12-30-09Z {
dimensions:
	time = UNLIMITED ; // (1 currently)
	lat = 160 ;
	lon = 320 ;
	mcmc_sample_index = 240 ;
variables:
	double time(time) ;
		time:long_name = "time" ;
	double lat(lat) ;
		lat:long_name = "Latitude" ;
		lat:units = "degrees_north" ;
	double lon(lon) ;
		lon:long_name = "Longitude" ;
		lon:units = "degrees_east" ;
	float ar_probability(time, lat, lon) ;
		ar_probability:long_name = "posterior AR flag" ;
		ar_probability:units = "probability" ;
	int64 mcmc_sample_index(mcmc_sample_index) ;
	double area_threshold(time, mcmc_sample_index) ;
		area_threshold:long_name = "Area Threshold" ;
		area_threshold:units = "m^2" ;
	double filter_width(time, mcmc_sample_index) ;
		filter_width:long_name = "Gaussian Filter Width" ;
		filter_width:units = "degrees" ;
		filter_width:note = "width is half-height-half-mass" ;
	double segmentation_threshold(time, mcmc_sample_index) ;
		segmentation_threshold:long_name = "Segmentation Threshold" ;
		segmentation_threshold:units = "percentile" ;
	int64 ar_count(time, mcmc_sample_index) ;
		ar_count:long_name = "AR Detections" ;
		ar_count:units = "count" ;
}
```

The python implementation simply outputs one netCDF file per timestep, which is also probably not optimal.  Ideally the native CFWriter would be able to interact with a reduce stage that groups timesteps in some way (by month, by year, etc.) and outputs files following a templated name.

This is contingent on #99 and #151

**Comment by burlen** [comment]
fixed
