### ISSUE TITLE
profile performance of the teca_bayesian_ar_detect algorithm

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#252]
my approach might be described as follows

1. #248 
2. enable gcc auto vectorizer output, compile and inspect the diagnostics for the component algorithms.
3. run with gprof/cachegrind or other tools on a single node
4. dig into MPI parlallel issues

given teca's threaded execution model throughput and efficiency are co-dependent. eg  when thread are not pinned cash misses stall execution degrading performance, eg when threads are not pinned memory is more likely to allocated on external banks increasing numa affects.

**Comment by burlen** [comment]
#248 is done

**Comment by taobrienlbl** [comment]
@ndkeen - I'll be chatting with you about this in 45 mins.

Right now, the `teca_bayesian_ar_detect` algorithm is in the branch teca_bayesian_ar_app, which is up-to-date with master.  General build/install instructions are at [teca.readthedocs.org](https://teca.readthedocs.io/en/sphinx_documentation/).

# Building

For NERSC installation, there are a couple minor modifications (1) using the GNU compilers, (2) manually adding mpich to `PKG_CONFIG_PATH`, and (3) adding `-DENABLE_CRAY_MPICH=true` to cmake.  I've been using a script similar to the following to build:
```bash
#!/bin/bash 
module swap PrgEnv-intel PrgEnv-gnu
module swap gcc gcc/6.1.0
export MYCC=`which gcc`
export MYCXX=`which g++`
export MYFC=`which gfortran`

module load python3
# load a custom python environment that contains TECA pre-requisites
source activate climate-notebook
module load cmake

# re-set CC/CXX/FC, since `source activate ...` overwrites this
export CC=$MYCC
export CXX=$MYCXX
export FC=$MYFC

# mpich is not in the pkg-config path on Cori/Edison
# I have reported this bug to NERSC. for now we
# must add it ourselves.
export PKG_CONFIG_PATH=$CRAY_MPICH_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

# set the the path where TECA is installed to.
# this must be a writable directory by the user
# who is doing the build, as install is progressive.
TECA_INSTALL=$PWD/install

BUILD_DIR=$PWD/bld
# do a clean build if indicated on the command line
if [ "$1" == "clean" ]; then
    if [ -d "$BUILD_DIR" ]; then
        rm -rf $BUILD_DIR
    fi
    mkdir -p $BUILD_DIR
cd $BUILD_DIR


# Configure TECA superbuild
cmake \
    -DCMAKE_CXX_COMPILER=$CXX \
    -DCMAKE_C_COMPILER=$CC \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_CRAY_MPICH=true \
    -DCMAKE_INSTALL_PREFIX=${TECA_INSTALL} \
    ..
fi

cd $BUILD_DIR
make -j 8 install
```

# Running the test
Once the build completes and the `PATH` and `LD_LIBRARY_PATH` variables are set appropriately, you should be able to run a test of the AR detector with the following command line:

```bash
teca_bayesian_ar_detect --input_file /project/projectdirs/m1517/cascade/external_datasets/era_20cr/ivt/e20c.oper.an.sfc.3hr.162_IVT.regn80sc.1983010100_1983123121.nc4 --last_step 0
```

The above file has 2920 timesteps, and (I think) timesteps will be divided among MPI processes, so this is probably a good candidate for scaling tests up to 2920 nodes. (@burlen - am I right on this, or is it that the output files are split among MPI processes?  So if there are 8 timesteps per file, then if this is the case, would 365 be the max MPI size for this file?).  There are more files in that directory, so you could use more for larger-scale tests.

In my mind, there are three main questions to answer here:
 1. What function(s) take up the most time in a single-core version?
 2. Does this differ as MPI and/or thread count increases?
 3. What are the weak and strong scaling characteristics of this app?

Number 3 is particularly important, since we'll shortly be submitting a cori@scale application: we'll need a figure on this.

**Comment by ndkeen** [comment]
I did try the generic build instructions and it failed.  Trying this script, I first needed to unload the python module that was loaded so that the one above could be loaded.  Then I got:

```
cori07% source activate climate-notebook
activate: No such file or directory.
```

**Comment by taobrienlbl** [comment]
We just e-mailed about this, but for completeness, here is the script I use to create that environment, which is installed in my user space:

```bash
#!/bin/bash

module load python3
conda create -n climate-notebook python=3.6.7 --quiet --yes
source activate climate-notebook
conda install -c conda-forge --quiet --yes \
    'conda-forge::blas=*=openblas' \
    'conda-forge::ipywidgets=7.4*' \
    'conda-forge::pandas=0.23*' \
    'conda-forge::numexpr=2.6*' \
    'conda-forge::matplotlib=2.2*' \
    'conda-forge::scipy=1.2*' \
    'conda-forge::seaborn=0.9*' \
    'conda-forge::scikit-learn=0.20*' \
    'conda-forge::scikit-image=0.14*' \
    'conda-forge::sympy=1.1*' \
    'conda-forge::cython=0.28*' \
    'conda-forge::patsy=0.5*' \
    'conda-forge::statsmodels=0.9*' \
    'conda-forge::cloudpickle=0.5*' \
    'conda-forge::dill=0.2*' \
    'conda-forge::numba=0.38*' \
    'conda-forge::bokeh=0.13*' \
    'conda-forge::sqlalchemy=1.2*' \
    'conda-forge::hdf5=1.10*' \
    'conda-forge::h5py' \
    'conda-forge::libpng' \
    'conda-forge::ipympl' \
    'conda-forge::vincent=0.4.*' \
    'conda-forge::beautifulsoup4=4.6.*' \
    'conda-forge::protobuf=3.*' \
    'conda-forge::xarray' \
    'conda-forge::emcee' \
    'conda-forge::cartopy=0.17*' \
    'conda-forge::geopandas' \
    'conda-forge::gdal' \
    'conda-forge::krb5' \
    'conda-forge::expat' \
    'conda-forge::gitpython' \
    'conda-forge::netCDF4' \
    'conda-forge::mpi4py=2*' \
    'conda-forge::tornado=5.1.*' \
    'conda-forge::basemap' \
    'cascade::climextremes' \
    'conda-forge::libgfortran' \
    'conda-forge::xlrd'
conda remove --quiet --yes --force qt pyqt
conda clean -tipsy
# Activate ipywidgets extension in the environment that runs the notebook server
#jupyter nbextension enable --py widgetsnbextension --sys-prefix
## Also activate ipywidgets extension for JupyterLab
## Check this URL for most recent compatibilities
## https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/jupyterlab-manager
#jupyter labextension install @jupyter-widgets/jupyterlab-manager@^0.38.1
#jupyter labextension install jupyterlab_bokeh@0.6.3
#jupyter labextension install jupyterlab_vim && \
#jupyter labextension install jupyter-matplotlib && \
pip install fastkde && \
pip install f90nml
```

I should also note that I installed mpi4py separately using `cc`, `CC`, and `ftn` as the compilers, in order for the python bindings to work properly at NERSC: that won't be necessary here though.

**Comment by taobrienlbl** [comment]
@ndkeen - see also Burlen's post on TECA using KNL: https://cascade-climate.atlassian.net/wiki/spaces/TECA/blog/2017/05/12/72515594/TECA+On+KNL

**Comment by taobrienlbl** [comment]
The above script is definitely overkill (and was missing swig, which I installed manually, apparently).  I found this in an earlier exchange with Burlen:

```bash
conda create --yes -c conda-forge -n teca_conda python=3.6 numpy mpi4py netCDF4 boost openmpi matplotlib python-dateutil cython swig pyparsing cycler pytz
```

@elbashandy - we might want to add the above to the sphinx documentation (and double check that it reliably works)

**Comment by ndkeen** [comment]
Noting that the above `conda create` command did work for me.  I was able to build the default branch of TECA with it. And I also just built the `teca_bayesian_ar_app` branch as well.

I have not yet modified anything to build for KNL's. I will rebuild with notes from the above-mentioned `TECA+On+KNL` notes. This is just test that I have right env and can build, etc.

**Comment by taobrienlbl** [comment]
A quick follow-up on an erroneous comment that I made:

> The above file has 2920 timesteps, and (I think) timesteps will be divided among MPI processes, so this is probably a good candidate for scaling tests up to 2920 nodes. (@burlen - am I right on this, or is it that the output files are split among MPI processes? So if there are 8 timesteps per file, then if this is the case, would 365 be the max MPI size for this file?)

I was mistaken in the original statement, and @burlen confirmed in person that what I said in parentheses is correct.  The finest granularity for MPI is at the output file level. If we output files with 8 timesteps per file, then 2920/8 = 365 files; so the max MPI size is 365 in this specific case.

**Comment by ndkeen** [comment]
I'm unable to run the executable -- either on the command line (just as a test) or in a batch environment.

I set LD_LIBRARY_PATH to include the path to the teca_conda lib as well as the TECA lib dir.

```
(teca_conda) ndk@cori07:/global/cscratch1/sd/ndk/teca> echo $LD_LIBRARY_PATH
/opt/gcc/7.3.0/snos/lib64:/opt/cray/job/2.2.3-6.0.7.1_5.44__g6c4e934.ari/lib64:/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64:/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64:/usr/syscom/nsg/lib:/global/cscratch1/sd/ndk/teca/teca_bayesian_ar_app-TECA/install/lib:/global/u1/n/ndk/.conda/envs/teca_conda/lib
(teca_conda) ndk@cori07:/global/cscratch1/sd/ndk/teca> 
(teca_conda) ndk@cori07:/global/cscratch1/sd/ndk/teca> /global/cscratch1/sd/ndk/teca/teca_bayesian_ar_app-TECA/install/bin/teca_bayesian_ar_detect 
/global/cscratch1/sd/ndk/teca/teca_bayesian_ar_app-TECA/install/bin/teca_bayesian_ar_detect: error while loading shared libraries: libboost_program_options.so.1.67.0: cannot open shared object file: No such file or directory
(teca_conda) ndk@cori07:/global/cscratch1/sd/ndk/teca>
```

**Comment by taobrienlbl** [comment]
Are you possibly mixing up the `climate-notebook` binary with the `teca_conda` environment?  The will likely have different .so revisions.

**Comment by burlen** [comment]
The number of time steps per file controls how many time steps are processed per rank. We did it that way to avoid dealing with I/O coordination & synchronization issues when multiple ranks write into the same netcdf file.

**Comment by burlen** [comment]
FYI I added `--parameter_table::number_of_rows 256` on Travis's branch to aid in making profiling runs. if it is not set the full table is served

**Comment by burlen** [comment]
note: `--parameter_table::number_of_rows n` where `n = 2*i + 1` for all `i >= 0` , (ie. n is odd) reproduces the crash reported in  #215. until we fix #215, it is best to use even number of rows.

**Comment by burlen** [comment]
`CMAKE_CXX_FLAGS:STRING=-fPIC -std=c++11 -Wall -Wextra -g3 -O3 -DNDEBUG -march=native -mtune=native -fopt-info`

5x speedup over debug build

**Comment by ndkeen** [comment]
I can create another issue or doc location, but I'm actually no longer able to build TECA.

Previously, Travis and I ran some of the above steps on terminal. When I tried using the smaller subset:

`conda create --yes -c conda-forge -n ${cenv} python=3.6 numpy mpi4py netCDF4 boost openmpi matplotlib python-dateutil cython swig pyparsing cycler pytz`

It looked like it worked, but now I'm unable to repeat.

Here is the script I'm using. I wanted to be able to start from scratch. That is, download/build the conda env if I want, and checkout new clone of TECA repo.

`/global/cscratch1/sd/ndk/run-teca/g.bash`

The current error


```
[  9%] Building CXX object core/CMakeFiles/teca_core.dir/teca_dataset.cxx.o
/global/cscratch1/sd/ndk/teca/TECA-teca_conda03g-master-03master/apps/teca_metadata_probe.cpp:16:37: fatal error: boost/program_options.hpp: No such file or directory
 #include <boost/program_options.hpp>
                                     ^
compilation terminated.
apps/CMakeFiles/teca_metadata_probe.dir/build.make:62: recipe for target 'apps/CMakeFiles/teca_metadata_probe.dir/teca_metadata_probe.cpp.o' failed


And this is after cmake reports that it does find boost:

-- Found Boost 1.70.0 at /global/homes/n/ndk/CONDA_ENVS_PATH_teca_conda03g/teca_conda03g/lib/cmake/Boost-1.70.0
--   Requested configuration: QUIET COMPONENTS program_options
-- Found boost_headers 1.70.0 at /global/homes/n/ndk/CONDA_ENVS_PATH_teca_conda03g/teca_conda03g/lib/cmake/boost_headers-1.70.0
-- Found boost_program_options 1.70.0 at /global/homes/n/ndk/CONDA_ENVS_PATH_teca_conda03g/teca_conda03g/lib/cmake/boost_program_options-1.70.0
--   libboost_program_options.a
-- Adding boost_program_options dependencies: headers
Boost  found.
Found Boost components:
   program_options
-- Boost features -- enabled

```

**Comment by burlen** [comment]
I profiled the code today using callgrind with the above compiler options, it is showing that 70% of the time is spent in `teca_binary_segmentation`. This makes sense, as we are segmenting based on a percentile. Computing the percentile is based on a partial sort which is an expensive operation.

![teca_profile](https://user-images.githubusercontent.com/115053/60138002-9dff0780-975d-11e9-9b25-7dd317947dc1.png)

**Comment by burlen** [comment]
A couple of iterations made see (b90ffdf, ff15459, 9f4473d) the sort is down to 52% of run time. It's still dominating.

![teca_profile_3](https://user-images.githubusercontent.com/115053/60284369-37dec580-98c0-11e9-8f55-48357e7af174.png)
