### ISSUE TITLE
TECA app for running ML model

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#259]
The following summarizes a meeting between @elbashandy and @taobrienlbl about implementing a Python-based TECA app for running a pytorch-based AR detection.

* Ankur has trained a Pytorch model that takes map of IVT or IWV as input (depending on the model) and provides a map of 'probability of AR occurrence' as output
* The idea here would be to implement a TECA app that essentially works as a wrapper for Ankur's ML model - and for pytorch-based models like his in general
* The app would have three main components in the pipeline:
 1. a `teca.teca_cfreader()`
 2. a teca programmable algorithm that, in its `execute` stage, feeds IVT or IWV into the pytorch model as a numpy array
 3. a `teca.teca_cfwriter()` component for writing the AR probabilities to disk.

The idea would be that the app works in essentially the same way as the bayesian AR detector app (#258), but using the ML model instead of the bayesian method.

**Comment by burlen** [comment]
see https://pytorch.org/cppdocs/

**Comment by elbashandy** [comment]
I converted the model into TorchScript as mentioned [here](https://pytorch.org/cppdocs/) in case we implement teca_model_segmentation in C++. The model is on hobb
