### ISSUE TITLE
timing information

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#267]
@ndkeen - @burlen  and I spoke this afternoon about adding timing information to TECA.  @burlen indicates that there is a central place in the code where this could be added to get timing information on all components of the pipeline.

I'm creating this issue/feature-request to start a conversation about this.

**Comment by burlen** [comment]
[timer.gz](https://github.com/LBL-EESA/TECA/files/3399305/timer.gz)

**Comment by burlen** [comment]
Abdel and I finished this one. Note: locking in the log could impact performance when large numbers of threads per rank are used, eg bayesian ar detector. For this reason our profiler should be used for diagnostics rather than bench marks.
