### ISSUE TITLE
Question: do we change the python interface to avoid the use of `.New()` when constructing objects?

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#271]
The advantage of this change would be that the TECA python interface is more pythonic: perhaps easier to for new users to learn.  @burlen  suggests that we might do this by writing a wrapper for the Python interface that would hide the `.New()` call: likely by doing this within the __init__() function.

A disadvantage would be that the python API would diverge from the C++ API.

**Comment by burlen** [comment]
also, what other changes should we make to make teca easier to use in Python?
