### ISSUE TITLE
handle string attributes

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#303]
Getting the following error:
`ERROR:` netcdf type code 12 is not supported`

When running on any of these files:
`/project/projectdirs/m1517/cascade/taobrien/artmip/tier2/sharing/cmip6/windhusavi/BCC-CSM2-MR/'.*\.nc'`

We discussed this via zoom on 10/24/19

**Comment by burlen** [comment]
@taobrienlbl Can you open the permission?

```
~$cp /project/projectdirs/m1517/cascade/taobrien/artmip/tier2/sharing/cmip6/windhusavi/BCC-CSM2-MR/windhusavi_6hrLev_BCC-CSM2-MR_historical_r1i1p1f1_gn_195001010000-195001190000.nc ./   
cp: cannot open '/project/projectdirs/m1517/cascade/taobrien/artmip/tier2/sharing/cmip6/windhusavi/BCC-CSM2-MR/windhusavi_6hrLev_BCC-CSM2-MR_historical_r1i1p1f1_gn_195001010000-195001190000.nc' for reading: Permission denied
```

**Comment by taobrienlbl** [comment]
@burlen  - here, I should have pointed you to this directory, which has open permissions: 

`/project/projectdirs/m1517/www/cascade/artmip/tier2/cmip6/windhusavi/BCC-CSM2-MR`

**Comment by burlen** [comment]
See #304.  because of the power outage I can't access the data to test it yet.

**Comment by burlen** [comment]
fixed
