### ISSUE TITLE
Document teca_bard_v1

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#318]

**Comment by burlen** [comment]
@taobrienlbl Is this something I should take on?

**Comment by elbashandy** [comment]
I added a simple documentation of TECA-BARD in PR #416  as it required little work from me because I just documented the Deeplab algorithm.

**Comment by taobrienlbl** [comment]
Thanks @elbashandy!

**Comment by burlen** [comment]
resolved by #511
