### ISSUE TITLE
move teca_binary_segmentation::set_segmentation_variable_atts to teca_cf_writer

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#319]
This method in binary segmentation passes datasets attributes that are put in the output dataset. The only use case I currently see is in the Bayesian AR detector where it is used to get file level attributes into the output dataset. However this is generally useful/necessary feature as these attributes are needed in the dataset written to disk so that it may later be interpreted. I think this method/functionality could be moved to the CF writer.  Another option might be an algorithm's whose sole purpose is for injecting user supplied dataset attributes.

**Comment by burlen** [comment]
@taobrienlbl thoughts on making this more general?

**Comment by taobrienlbl** [comment]
I definitely agree about making it more general, and I had a similar thought when writing it.

I like the idea of having a general purpose algorithm that injects user-supplied attributes.  This keeps the functionality separate from the output file format.  Say for example we adopt an xml file format someday for outputting polygon information, we wouldn't have to re-implement this functionality in the xml writer; we'd just have to make sure that the xml writer appropriately writes metadata associated with output variables.

**Comment by burlen** [comment]
I was mistaken in my assessment, the attributes are associated to the output variable generated by the segmentation algorithm and therefore are not stored in the file level.

It makes sense to have the algorithm generating the variable set it's attributes. However, having an API that lets the user inject the attributes complicates things. For instance imagine an algorithm that sets attributes like "units". What would happen if the user then also specified attributes through this API? who's attributes win? Or is it the union of attributes? How is that implemented and does each algorithm then implement it?

I wonder if the binary segmentation (and other algorithms) could set attribute automatically? For instance what if the segmentation added an attribute: 

| attribute name | description                                                        |
|---------------------|--------------------------------------------------------------|
| description       | binary segmentation of [INPUT VAR NAME] . Low threshold [LOW VALUE]. High threshold [HIGH VALUE]. Mode [PERCENTILE / BY VALUE]. |

We could generalize this by adopting a convention that for each new variable generated by an algorithm we add a "description" attribute associated with that variable. We could potentially add other attributes that make it easier to parse by a later consumer. Of course a "units" attribute would make sense as well.
 
In the case of the Bayesian AR detector app it seems like some of the other attributes injected into the binary segmentation could actually be placed in attributes at file scope. For instance information about the version of the app and the scheme employed. Version would probably be best satisfied by using the TECA_VERSION_DESCR which is a CPP define based on the git version, release number and sha if not on a release. 

Then again I'm not sure if these changes would be consistent with ARTMIP's requirements? 

Would be useful for having a pathway in the writer to set file scope attributes similar to what we have in the binary segmentation.

**Comment by burlen** [comment]
this was addressed with parallel collective I/O for the CF writer. Generally individual algorithms may need API for injecting attributes. A new class `teca_array_attributes` was added to normalize the set of attributes and implement convenience API's for dealing with them.
