### ISSUE TITLE
create docker image for Travis CI with latest Ubuntu  release

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#333]
create docker image for Travis CI with latest Ubuntu  release. 18.04 is ~ 2 yo, especially with Ubuntu because its packages are old to begin with we should stay ahead of our users in testing on new OS releases. When the new image is in place , retire the 18.04 image.

**Comment by burlen** [comment]
@elbashandy this is becoming high priority. fedora image should be updated as well.

**Comment by burlen** [comment]
@elbashandy I will update the fedora image

**Comment by elbashandy** [comment]
@burlen sounds good. I looked up ubuntu and 18.04 is still the lastest stable release.

**Comment by burlen** [comment]
20.04 is the next LTS and should be finalized soon - end of month? Let's hold off until end of April to see if it is out.

**Comment by burlen** [comment]
do not merge without #393
