### ISSUE TITLE
numpy issue: *** Reference count error detected:  an attempt was made to deallocate 11 (f) ***

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#34]
the entire test suiet should be valgrind clean. the following leaks a table, I think it's being returned from the python callback.

`valgrind --leak-check=full --track-origins=yes /bin/python "/home/bloring/work/teca/teca/test/python/test_programmable_map_reduce.py" "/home/bloring/work/teca/teca/bin/../../TECA_data//cam5_1_amip_run2\.cam2\.h2\.1991-10-0[12]-10800\.nc" "py_test_programmable_map_reduce.bin" "0" "-1" "TMQ" "T200" "T500"`

**Comment by Zulfidin** [comment]
I am new to programming,

I am getting the same error when trying to use numpy in Jetson Tx2,
I don't understand what did you do fix this issue ?

**Comment by burlen** [comment]
We fixed the issue a few years ago, I don't now remember the details. It may have been related to not aquiring the GIL. Are you using teca? Or is this related to Jetson tx2? If the latter you should ask them

**Comment by Zulfidin** [comment]
Thank you, I am using Jetson TX2.

**Comment by burlen** [comment]
i see, best to report the issue to them, as it is likely a bug on their side
