### ISSUE TITLE
macos tests don't error-out if svn co from TECA_data repo fails

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#341]
The linux tests for TravisCI fail when this happens, but it appears that the macos tests don't fail.  These should have consistent behavior, and triggering an error is probably the correct behavior for the test suite.

**Comment by burlen** [comment]
I'm not sure what the source of the issue was but we haven't seen this one in a while so I'll close it. @taobrienlbl  please re-open if I'm wrong about this.
