### ISSUE TITLE
run deeplab ar detector on cori GPU nodes

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#348]
1. verify the deeplab detector works on the cori gpu nodes.
2. verify that it is faster than when run on the cpu
3. document options for using gpu in rtd docs(see issue #349)

**Comment by burlen** [comment]
@taobrienlbl who should take this on? I think it would be either you or Abdel - probably Abdel?

**Comment by taobrienlbl** [comment]
@ndkeen - do you have an account on the Cori GPU cluster, or do you think you could get one easily?  And would this be of interest? We're looking to examine the performance of the new TECA Machine Learning AR detector on GPU nodes vs CPU nodes.

@elbashandy or I can provide a test problem.

**Comment by elbashandy** [comment]
Yes thanks for bring this up @burlen. Can we use TECA's current profiling component in this evaulation?

**Comment by burlen** [comment]
> Yes thanks for bringing this up @burlen. Can we use TECA's current profiling component in this evaulation?
@elbashandy One could do that. There are some reasons we might hold of on such low level profiling at first (better discussed over zoom). To start we could get a quick and dirty validation that things are working as expected. The bash `time` command would probably do the trick. Or if you run in a batch script slurm will time it for you. Batch scripts also document the test and make it easy to reproduce.

**Comment by burlen** [comment]
#534 gets the deeplab ar detector app working with CUDA.
