### ISSUE TITLE
missing RTD documentation for deeplab ar detector

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#349]
add documentation for the command line application in the RTD site
use the same format/layout/style as other apps

**Comment by burlen** [comment]
@elbashandy status? this is now holding me up as I need to document running with MPI...

**Comment by elbashandy** [comment]
@burlen will get to it asap. Can you give a brief description here and I will add it to RTD? I want to understand how you tackled the MPI issue

**Comment by burlen** [comment]
I'm sorry, I don't have time, but you can read about it in the RTD docs. Let's get that in place.

**Comment by elbashandy** [comment]
No worries, I understand. Will get it in place :)

**Comment by burlen** [comment]
See #416
