### ISSUE TITLE
deeplab ar detector missing ar_binary_tag

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#357]
we are writing ar_probability but the ar_binary_tag is not being computed. for parity with the Bayesian ar detector add ar_binary_tag field.

**Comment by burlen** [comment]
@taobrienlbl is this something that we should address?

**Comment by taobrienlbl** [comment]
thanks for catching this.  Yes: the 'ar_binary_tag' field is mandatory for submission to ARTMIP

**Comment by elbashandy** [comment]
@burlen @taobrienlbl This tag is being used by the binary segmentation algorithm. Do we need to add it to the pipeline as well?

**Comment by burlen** [comment]
yes, you can copy what Travis did in his application

**Comment by elbashandy** [comment]
See #359
