### ISSUE TITLE
teca_binary_segmentation alg output is giving outbound values

### ISSUE THREAD

**Issue by elbashandy** [LBL-EESA/TECA#362]
The output values are less than 0 and greater than 1

I tested the teca_deeplabv3_ar_detect app pipeline on CAM5 and ARTMIP datasets. To be specific, on:
`ARTMIP_MERRA_2D_20170210_[00-21].nc`
&
`IVT_CAM5-1-0.25degree_All-Hist_est1_v3_run1.cam2.h4.2015-04-01-00000.nc`

The command:
```
python3 bin/teca_deeplabv3p_ar_detect --input_regex /project/artmip/"ARTMIP_MERRA_2D.*\.nc" --t_axis_variable "" --filename_time_template "ARTMIP_MERRA_2D_%Y%m%d_%H.nc" --t_units "days since 1979-01-01 00:00:00" --steps_per_file 8 --date_format "%Y%m%d" --output_file /project/artmip/"MERRA2.ar_prob.cascade_deeplab_v1.3hourly.%t%.nc4"
```

![outbound_binary_indicator](https://user-images.githubusercontent.com/1439632/82624767-413be500-9b98-11ea-9acb-3e0a6d34be12.png)

**Comment by burlen** [comment]
I can reproduce it, it ahppens in Bayesian AR detector too. Must be related to recent I/O changes
```
./bin/teca_bayesian_ar_detect --input_file /work2/data/teca/merra_2_ar/ARTMIP_MERRA_2D_20170516_00.nc  --cf_reader::filename_time_template ARTMIP_MERRA_2D_%Y%m%d_%H.nc --cf_reader::t_axis_variable ""
```

**Comment by burlen** [comment]
fixed
