### ISSUE TITLE
use templates instead of casting as double in teca_metadata_probe

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#375]
@burlen - I mentioned on Friday that I had a problem running `teca_metadata_probe` on some ERA5 data.

There seems to be a bug in `teca_metadata_probe` that renders it unable to parse ERA5 netCDF files, because they use an integer-valued time coordinate.  The file is readable by TECA, as a python-based pipeline successfully parses the file.  This suggests that there is no problem with the cf_reader itself, but rather there is a problem with the implementation in `teca_metadata_probe`. In attempting to debug this, I noticed that ERA5 uses integer-typed time values.  However, `teca_metadata_probe` is attempting to typecast a double:

[lines 174-181](https://github.com/LBL-EESA/TECA/blob/7aa87914efea17fea342b3b4d1c3ac1ea8d36272/apps/teca_metadata_probe.cpp#L174)
```c++
    teca_metadata coords;
    p_teca_double_array time;
    if (md.get("coordinates", coords)
       || !(time = std::dynamic_pointer_cast<teca_double_array>(coords.get("t"))))
    {
        TECA_ERROR("failed to determine time coordinate")
        return -1;
    }
```

I suspect that the fix would be to wrap this in templating code.  @burlen: could you tackle this please?  I'm only marginally competent with C++ templating, and this would likely take me 10x longer than it would take you.

**Comment by taobrienlbl** [comment]
Also, here is a path to a test file at NERSC: `/global/cscratch1/sd/taobrien/sharing/teca_metadata_probe_bug/e5.oper.an.vinteg.162_071_viwve/e5.oper.an.vinteg.162_071_viwve.ll025sc.1979100100_1979103123.nc`

**Comment by burlen** [comment]
@taobrienlbl yes, you have found the problem. I'll push something shortly.
