### ISSUE TITLE
option to avoid use of metadata cache in cf_reader

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#377]
It would be nice to have a global option to disable the cf_reader's use of metadata caching.

The metadata cache can make debugging I/O-related issues difficult. For example, in diagnosing #375, I had to do multiple invocations of `teca_cf_reader`: in one particular test, the use of the metadata cache led to a confusing/misleading result.  I only realized this after I got a different result when I deleted the cache file. This results in needing to delete cache files as part of a modify-run-debug workflow.

A global option--possibly enabled by setting an environment variable--would greatly simplify the debugging workflow and would lead to fewer false positives/negatives when running tests to debug I/O-related issues: e.g., using `export TECA_CFREADER_CACHE=0` to disable use of cache in all TECA programs.

**Comment by burlen** [comment]
this was implemented in a4c5ed3f441f
