### ISSUE TITLE
error callback

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#38]
add support for an error callback. this involves storing the callback (threadsafe singleton pattern) and invoking it from TECA_ERROR.

this will give applications the flexibility to react to errors. the first place we will use this is in our regression test suite. in the presence of an error we can fail the test immediately. we'll also use it in command line applications.

**Comment by taobrienlbl** [comment]
@taobrienlbl and @burlen just discussed this - it would solve an issue that @taobrienlbl  has been seeing in python, where internal TECA errors don't get raised as exceptions in python: for example, path errors to `teca_cf_reader`.
