### ISSUE TITLE
use new cropped dataset for all AR tests

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#392]
The new test dataset `ARTMIP_MERRA_2D_2017-05-16-00Z.nc` contains 8 time steps and captures an AR on the North Americal Pacific coast. Replace the old ARTMIP_MERRA time series with this one for all tests that had previously used them.  The This is in TECA_data revision 67.

**Comment by burlen** [comment]
#372 now has updates to use the new dataset in the Bayesian AR detector tests

**Comment by elbashandy** [comment]
Resolved by #372
