### ISSUE TITLE
Use Parallel NetCDF in Ubuntu Travis CI

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#393]
In the CMake output you will see:
```
-- NetCDF features -- enabled
-- Check NetcCDF for MPI support -- not found
```
The last line should say enabled, parallel CF writer tests will not work without this.

Should be done as a part of #333

**Comment by burlen** [comment]
in 18.04 I could not find a pre-built package (ala apt). This may require us to install parallel hdf5, and compile netcdf from sources. Given this we might consider transitioning to using the superbuild instead of apt.

**Comment by taobrienlbl** [comment]
that seems sensible; if we can't get binary packages for the dependencies we need, then we have to compile. IMO, the superbuild should be our only supported way of building TECA when TECA's dependencies can't be provided in pre-built binaries.

**Comment by burlen** [comment]
Good point. I think this may impact our PyPi package as well. pip installing on ubuntu will result in serial hdf5/netccdf.

**Comment by burlen** [comment]
See also #401

**Comment by elbashandy** [comment]
@burlen @taobrienlbl just to confirm, I will proceed with building the packages using TECA_superbuild

**Comment by taobrienlbl** [comment]
Yes, that's right, since ubuntu/debian doesn't provide deb packages for parallel netcdf (unless you find some).

**Comment by elbashandy** [comment]
I only found [`libhdf5-mpich-dev`](https://packages.ubuntu.com/search?keywords=libhdf5-mpich-dev) & [`libhdf5-mpi-dev`](https://packages.ubuntu.com/search?keywords=libhdf5-mpi-dev)for hdf5, [`libnetcdf-mpi-dev`](https://packages.ubuntu.com/search?keywords=libnetcdf-mpi-dev) & `libnetcdf-pnetcdf-dev` for netcdf.

When I installed `libnetcdf-mpi-dev` I got this error:

```
error: NetCDF: Parallel operation on file opened for non-parallel access

stack:
92: [2ca6240699bc:02806] Read -1, expected 131072, errno = 1
92: [2ca6240699bc:02806] Read -1, expected 131072, errno = 1
92: [2ca6240699bc:02806] Read -1, expected 131072, errno = 1
92: [2ca6240699bc:02806] Read -1, expected 131072, errno = 1
92: [2ca6240699bc:02806] Read -1, expected 130009, errno = 1
92: STATUS: [1:140338986186560] [/project/TECA/io/teca_cf_reader.cxx:1028 3.0.0-135-g4d0f6b1]
92: STATUS: Wrote metadata cache "/project/TECA_data/7ae6e568c48c5062b6e1c52e52f0bada6f68816c.tmd"
92: ERROR: [1:140338986186560] [/project/TECA/io/teca_netcdf_util.cxx:196 3.0.0-135-g4d0f6b1]
92: ERROR: Failed to create "test_deeplabv3p_ar_detect_app_output_2017-05-16-00Z.nc". NetCDF: Parallel operation on file opened for non-parallel access
92: ERROR: [1:140338986186560] [/project/TECA/io/teca_cf_layout_manager.cxx:96 3.0.0-135-g4d0f6b1]
92: ERROR: failed to create file "test_deeplabv3p_ar_detect_app_output_%t%.nc"
92: ERROR: [0:139823838140224] [/project/TECA/io/teca_netcdf_util.cxx:196 3.0.0-135-g4d0f6b1]
92: ERROR: Failed to create "test_deeplabv3p_ar_detect_app_output_2017-05-16-00Z.ncERROR: [1:140338986186560] [/project/TECA/io/teca_cf_writer.cxx:282 3.0.0-135-g4d0f6b1]
92: ERROR: Failed to create file 0
92: ". NetCDF: Parallel operation on file opened for non-parallel access
92: ERROR: [0:139823838140224] [/project/TECA/io/teca_cf_layout_manager.cxx:96 3.0.0-135-g4d0f6b1]
92: ERROR: failed to create file "test_deeplabv3p_ar_detect_app_output_%t%.nc"
92: ERROR: [0:139823838140224] [/project/TECA/io/teca_cf_writer.cxx:282 3.0.0-135-g4d0f6b1]
92: ERROR: Failed to create file 0
```

Then I replaced it with `libnetcdf-pnetcdf-dev`, and I got a different error:

```
error: Failed to set inidependant mode on variable "ar_probability"

stack:
91: STATUS: [0:140476027914048] [/project/TECA/io/teca_cf_reader.cxx:405 3.0.0-135-gc088603]
91: STATUS: Found metadata cache "/project/TECA_data/aca75e3dca2b3aa7179365b1f96359f1037c91e8.tmd"
91: ERROR: [0:140476027914048] [/project/TECA/io/teca_cf_layout_manager.cxx:383 3.0.0-135-gc088603]
91: ERROR: Failed to set inidependant mode on variable "ar_probability"
91: ERROR: [0:140476027914048] [/project/TECA/io/teca_cf_writer.cxx:292 3.0.0-135-gc088603]
91: ERROR: failed to define file 0
91: /usr/local/lib/python3.8/dist-packages/torch/storage.py:34: FutureWarning: pickle support for Storage will be removed in 1.5. Use `torch.save` instead
91:   warnings.warn("pickle support for Storage will be removed in 1.5. Use `torch.save` instead", FutureWarning)

```
^ I guess this one is mentioned in the [documentation](https://www.unidata.ucar.edu/software/netcdf/docs/group__datasets.html#ga6dc46e4ab82584360518db5cb0cad841): "Note when file is opened/created to use PnetCDF library to perform parallel I/O underneath, argument varid is ignored and the mode changed by this function applies to all variables. This is because PnetCDF does not support access mode change for individual variables. In this case, users may use NC_GLOBAL in varid argument for better program readability" --- we are using `NC_INDEPENDENT` on line 380 in `teca_cf_layout_manager.cxx`

**Comment by burlen** [comment]
pnetcdf will not work, do not install.

netcdf-mpi-dev is the one you want.

```
NetCDF: Parallel operation on file opened for non-parallel access
```
This is likely happening because you've linked to the wrong library(i.e. the serial one). Make sure you do not install the serial or any other netcdf packages.

**Comment by elbashandy** [comment]
I deleted every package and started over by just installing `libnetcdf-mpi-dev` and these are the packages that got installed with it:

```
ii  libcaf-openmpi-3:amd64                 2.8.0-1                           amd64        Co-Array Fortran libraries  (OpenMPI)
ii  libcoarrays-openmpi-dev:amd64          2.8.0-1                           amd64        Co-Array Fortran libraries  - development files (OpenMPI)
ii  libhdf5-openmpi-103:amd64              1.10.4+repack-11ubuntu1           amd64        Hierarchical Data Format 5 (HDF5) - runtime files - OpenMPI version
ii  libnetcdf-mpi-13:amd64                 1:4.6.2-1                         amd64        Interface for scientific data access to large binary data
ii  libnetcdf-mpi-dev:amd64                1:4.6.2-1                         amd64        creation, access, and sharing of array-oriented scientific data
ii  libopenmpi-dev:amd64                   4.0.3-0ubuntu1                    amd64        high performance message passing library -- header files
ii  libopenmpi3:amd64                      4.0.3-0ubuntu1                    amd64        high performance message passing library -- shared library
ii  openmpi-bin                            4.0.3-0ubuntu1                    amd64        high performance message passing library -- binaries
ii  openmpi-common
```

I made sure that TECA picked up on the NetCDF parallel i/o feature:

```
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI_Fortran: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_usempif08.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- MPI features -- enabled
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- /usr/lib/x86_64-linux-gnu/netcdf/mpi/lib/libnetcdf.so
-- Found NetCDF: /usr/lib/x86_64-linux-gnu/netcdf/mpi/lib/libnetcdf.so  
-- NetCDF features -- enabled
-- Check NetCDF for MPI support -- enabled
```

Still getting the same error:

```
94: ERROR: [1:140490218683904] [/project/TECA/io/teca_netcdf_util.cxx:196 TECA-BARD-v1.0.1-10-gf309d52]
94: ERROR: Failed to create "test_bayesian_ar_detect_app_output.nc". NetCDF: Parallel operation on file opened for non-parallel access
94: ERROR: [1:140490218683904] [/project/TECA/io/teca_cf_layout_manager.cxx:96 TECA-BARD-v1.0.1-10-gf309d52ERROR: [0:140339829652992] [/project/TECA/io/teca_netcdf_util.cxx:196 TECA-BARD-v1.0.1-10-gf309d52]
94: ERROR: Failed to create "test_bayesian_ar_detect_app_output.nc". NetCDF: Parallel operation on file opened for non-parallel access
94: ERROR: [0:140339829652992] [/project/TECA/io/teca_cf_layout_manager.cxx:96 TECA-BARD-v1.0.1-10-gf309d52]
94: ERROR: failed to create file "test_bayesian_ar_detect_app_output.nc"
94: ERROR: [0:140339829652992] []
94: ERROR: failed to create file "test_bayesian_ar_detect_app_output.nc"
94: ERROR: [1:140490218683904] [/project/TECA/io/teca_cf_writer.cxx:/project/TECA/io/teca_cf_writer.cxx:282 TECA-BARD-v1.0.1-10-gf309d52]
94: ERROR: 282 TECA-BARD-v1.0.1-10-gf309d52]
94: ERROR: Failed to create file 0
94: Failed to create file 0
```

This still needs further investigation. I will go ahead and try installing the packages using TECA_superbuild.

**Comment by burlen** [comment]
@elbashandy hold of on using the superbuild, let's find out what is going on here

**Comment by burlen** [comment]
Among a number of problems with this package, it was apparently not compiled with MPI parallel features enabled. 

> **NC-4 Parallel Support:  no**

See below output from the settings file that documents how the library was configured. we can file a bug report with the package maintainer.  I am looking into that now. 

Note, that Cmake fails to find the broken package, `pc` file is not in the PKG_CONFIG_PATH and the `pc` file has a syntax error. Once I fixed the syntax error the `pc` file did not have the library path set correctly. So in order to get TECA to compile  I had to explicitly override the NETCDF_INCLUDE_DIR and NETCDF_LIBRARY(assuming Abdel had to do the same).

we could add some additional CMake code to verify but it will likely be obvious for most users that something is wrong with the package. Let's see what the response to a bug report is first.

/usr/lib/x86_64-linux-gnu/netcdf/mpi/libnetcdf.settings
```
# NetCDF C Configuration Summary                                                                                                                                                                                                                                 
==============================
  
# General
-------
NetCDF Version:     4.6.2
Build Directory:    /build/netcdf-parallel-oMW7Ac/netcdf-parallel-4.6.2/build-mpi
Install Prefix:         /usr
  
# Compiling Options
-----------------
C Compiler:     /usr/bin/mpicc
CFLAGS:         -g -O2 -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -DHDF5_PARALLEL -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O3 -DNDEBUG
CPPFLAGS:            
LDFLAGS:        -Wl,-Bsymbolic-functions -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-z,now 
AM_CFLAGS:          
AM_CPPFLAGS:        
AM_LDFLAGS:         
Shared Library:     yes 
Static Library:     no  
Extra libraries:    -lhdf5_hl -lhdf5_hl -lhdf5 -lhdf5 -lpthread -lsz -lz -ldl -lm -lcurl
  
# Features
--------
NetCDF-2 API:       yes
HDF4 Support:       no
NetCDF-4 API:       yes
NC-4 Parallel Support:  no  
PnetCDF Support:    no  
DAP2 Support:       yes 
DAP4 Support:       yes 
Diskless Support:   yes 
MMap Support:       no
JNA Support:        no
CDF5 Support:       yes 
ERANGE Fill Support:    yes 
Relaxed Boundary Check: yes
```

**Comment by burlen** [comment]
@elbashandy would you proceed with a manual install of netcdf?

the following steps worked for me

1. sudo apt-get install libhdf5-mpich-dev
2. wget netcdf c 4.7.4 tarball from unidata
3.  `./configure CC=mpicc CFLAGS="-O2 -g -I//usr/include/hdf5/mpich" LDFLAGS="-L/usr/lib/x86_64-linux-gnu/hdf5/mpich/ -lhdf5" --enable-parallel-4 --disable-dap --prefix=/home/user/netcdf-c-4.7.4-install/`
4. make -j && make -j install

**Comment by burlen** [comment]
@elbashandy please implement this as an option, to make the ubuntu 20.04 build either serial or parallel netcdf, and have travis ci run it both ways

**Comment by elbashandy** [comment]
@burlen Sounds good. Thanks for getting to the bottom of this
