### ISSUE TITLE
numpy and hdf5 error

### ISSUE THREAD

**Issue by bedassa** [LBL-EESA/TECA#407]
**On the screen**

Performing build step for 'numpy'
CMake Error at /home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/numpy-prefix/src/numpy-stamp/numpy-build.cmake:16 (message):
Command failed: 1

'env' 'CC=/usr/bin/gcc' 'CXX=/usr/bin/g++' 'CPPFLAGS=-I/home/bcheneka/Build_WRF/LIBRARIES/grib2/include -I/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/include' 'CFLAGS=-I/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/include -O3 -march=native -mtune=native -DNDEBUG' 'CXXFLAGS=-I/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/include -O3 -march=native -mtune=native -DNDEBUG' 'LDFLAGS=-L//home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib -L/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib64' 'LD_LIBRARY_PATH=/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib/:/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib64/:/opt/ud/devtoolset-8/root/usr/lib64:/opt/ud/devtoolset-8/root/usr/lib:/opt/ud/devtoolset-8/root/usr/lib64/dyninst:/opt/ud/openmpi-1.8.8/lib' 'DYLD_LIBRARY_PATH=/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib/:/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib64/:' 'PKG_CONFIG_PATH=/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib/pkgconfig:/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib64/pkgconfig:/lib/pkgconfig:' 'PATH=.:/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/bin/:/opt/ud/devtoolset-8/root/usr/bin:/opt/ud/openmpi-1.8.8/bin:/home/bcheneka/Build_WRF/LIBRARIES/python3.7/bin:/home/bcheneka/Build_WRF/LIBRARIES/py3k/bin:/opt/ud/Matlab-R2019b/bin:/home/bcheneka/Build_WRF/LIBRARIES/python3.7/bin:/home/bcheneka/Build_WRF/LIBRARIES/python3.7/condabin:/home/bcheneka/.local/bin:/home/bcheneka/Build_WRF/LIBRARIES/ncl/bin:/home/bcheneka/Build_WRF/LIBRARIES/jvm/jdk-14.0.1/bin:/home/bcheneka/Build_WRF/LIBRARIES/wgrib:/home/bcheneka/Build_WRF/LIBRARIES/cmake/bin:/home/bcheneka/Build_WRF/LIBRARIES/mpich/bin:/home/bcheneka/Build_WRF/LIBRARIES/netcdf-4.1.3/bin:/opt/ud/maui-3.3.1/bin:/opt/ud/torque-4.2.10/bin:/opt/ud/LOCAL/bin:.:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/bcheneka:/home/bcheneka/opt/bin:/usr/bin' 'PYTHONHOME=/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0' 'MPLBACKEND=Agg' 'PYTHONPATH=/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib:/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib/python3.7/site-packages/' 'NPY_DISTUTILS_APPEND_FLAGS=1' '/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/bin/python3' 'setup.py' 'build' 'install' '--prefix=/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0'

See also

/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/numpy-prefix/src/numpy-stamp/numpy-build-*.log
make[2]: *** [CMakeFiles/numpy.dir/build.make:113: numpy-prefix/src/numpy-stamp/numpy-build] Error 1
make[1]: *** [CMakeFiles/Makefile2:639: CMakeFiles/numpy.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMake Error at /home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/hdf5-prefix/src/hdf5-stamp/hdf5-configure.cmake:16 (message):
Command failed: 1

'env' 'CC=/usr/bin/gcc' 'CXX=/usr/bin/g++' 'CPPFLAGS=-I/home/bcheneka/Build_WRF/LIBRARIES/grib2/include -I/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/include' 'CFLAGS=-I/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/include -O3 -march=native -mtune=native -DNDEBUG' 'CXXFLAGS=-I/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/include -O3 -march=native -mtune=native -DNDEBUG' 'LDFLAGS=-L//home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib -L/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib64' 'LD_LIBRARY_PATH=/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib/:/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib64/:/opt/ud/devtoolset-8/root/usr/lib64:/opt/ud/devtoolset-8/root/usr/lib:/opt/ud/devtoolset-8/root/usr/lib64/dyninst:/opt/ud/openmpi-1.8.8/lib' 'DYLD_LIBRARY_PATH=/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib/:/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib64/:' 'PKG_CONFIG_PATH=/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib/pkgconfig:/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib64/pkgconfig:/lib/pkgconfig:' 'PATH=.:/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/bin/:/opt/ud/devtoolset-8/root/usr/bin:/opt/ud/openmpi-1.8.8/bin:/home/bcheneka/Build_WRF/LIBRARIES/python3.7/bin:/home/bcheneka/Build_WRF/LIBRARIES/py3k/bin:/opt/ud/Matlab-R2019b/bin:/home/bcheneka/Build_WRF/LIBRARIES/python3.7/bin:/home/bcheneka/Build_WRF/LIBRARIES/python3.7/condabin:/home/bcheneka/.local/bin:/home/bcheneka/Build_WRF/LIBRARIES/ncl/bin:/home/bcheneka/Build_WRF/LIBRARIES/jvm/jdk-14.0.1/bin:/home/bcheneka/Build_WRF/LIBRARIES/wgrib:/home/bcheneka/Build_WRF/LIBRARIES/cmake/bin:/home/bcheneka/Build_WRF/LIBRARIES/mpich/bin:/home/bcheneka/Build_WRF/LIBRARIES/netcdf-4.1.3/bin:/opt/ud/maui-3.3.1/bin:/opt/ud/torque-4.2.10/bin:/opt/ud/LOCAL/bin:.:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/bcheneka:/home/bcheneka/opt/bin:/usr/bin' 'PYTHONHOME=/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0' 'MPLBACKEND=Agg' 'PYTHONPATH=/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib:/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib/python3.7/site-packages/' 'CC=cc' 'CXX=CC' '/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/hdf5-1.10.5/configure' '--prefix=/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0' '--enable-hl' '--enable-build-mode=production' '--enable-parallel' '--enable-shared' '--disable-static'

See also

/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/hdf5-prefix/src/hdf5-stamp/hdf5-configure-*.log
make[2]: *** [CMakeFiles/hdf5.dir/build.make:106: hdf5-prefix/src/hdf5-stamp/hdf5-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:350: CMakeFiles/hdf5.dir/all] Error 2
make: *** [Makefile:117: all] Error 2

****In  hdf5 log file****

expr: syntax error
configure: error: unable to link a simple MPI-IO C program

**In numpy log file**

_configtest.c:1:5: warning: conflicting types for built-in function 'exp' [enabled by default]
int exp (void);
^
_configtest.o: In function main': /home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/numpy-1.17.2/_configtest.c:6: undefined reference to exp'
collect2: error: ld returned 1 exit status
_configtest.c:1:5: warning: conflicting types for built-in function 'exp' [enabled by default]
int exp (void);
^
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_bool':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src:112:5: note: use option -std=c99 or -std=gnu99 to compile your code
numpy/core/src/npysort/radixsort.c.src: In function 'aradixsort_bool':
numpy/core/src/npysort/radixsort.c.src:202:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_byte':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'aradixsort_byte':
numpy/core/src/npysort/radixsort.c.src:202:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_ubyte':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'aradixsort_ubyte':
numpy/core/src/npysort/radixsort.c.src:202:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_short':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'aradixsort_short':
numpy/core/src/npysort/radixsort.c.src:202:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_ushort':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'aradixsort_ushort':
numpy/core/src/npysort/radixsort.c.src:202:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_int':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'aradixsort_int':
numpy/core/src/npysort/radixsort.c.src:202:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_uint':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'aradixsort_uint':
numpy/core/src/npysort/radixsort.c.src:202:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_long':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'aradixsort_long':
numpy/core/src/npysort/radixsort.c.src:202:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_ulong':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'aradixsort_ulong':
numpy/core/src/npysort/radixsort.c.src:202:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_longlong':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'aradixsort_longlong':
numpy/core/src/npysort/radixsort.c.src:202:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'radixsort_ulonglong':
numpy/core/src/npysort/radixsort.c.src:112:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
numpy/core/src/npysort/radixsort.c.src: In function 'aradixsort_ulonglong':
numpy/core/src/npysort/radixsort.c.src:202:5: error: 'for' loop initial declarations are only allowed in C99 mode
for (npy_intp i = 1; i < num; i++) {
^
Running from numpy source directory.
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
warnings.warn(msg)
error: Command "/usr/bin/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/include -O3 -march=native -mtune=native -DNDEBUG -I/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/include -O3 -march=native -mtune=native -DNDEBUG -I/home/bcheneka/Build_WRF/LIBRARIES/grib2/include -I/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/include -fPIC -Ibuild/src.linux-x86_64-3.7/numpy/core/src/common -Inumpy/core/include -Ibuild/src.linux-x86_64-3.7/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/3.0.0/include/python3.7m -Ibuild/src.linux-x86_64-3.7/numpy/core/src/common -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.7/numpy/core/src/common -Ibuild/src.linux-x86_64-3.7/numpy/core/src/npymath -c build/src.linux-x86_64-3.7/numpy/core/src/npysort/radixsort.c -o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/numpy/core/src/npysort/radixsort.o -MMD -MF build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/numpy/core/src/npysort/radixsort.o.d" failed with exit status 1

**Comment by burlen** [comment]
What system are you trying to compile on? which superbuild options have you used? what version of gcc/g++ is this?

**Comment by bedassa** [comment]
I am aim to compile teca , for this I follow the steps provided. 
I use the following options 
$ git clone https://github.com/LBL-EESA/TECA_superbuild.git
$ cd TECA_superbuild
$ mkdir build
$ cd build
$cmake ..
$make -j 

The gcc /g++ versions are g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11).

**Comment by burlen** [comment]
I think I see the source of the problem. The TECA_superbuild makes use of very recent release of packages while Red Hat intentionally stays way behind. The versions of dependencies that we use will likely not compile on Red Hat. 

Also TECA requires newer compilers. GCC 4.8 C++11 support is known to be broken and TECA will be missing some key features even if you manage to compile with that compiler. At the very least you'll need to update to a newer gcc. You might as well take the latest gcc release.

We have not tested the TECA_super build on Red Hat systems. It will be difficult for us to provide detailed support for that system, due to lack of access to one and lack of time. I'm afraid you will need to work through build issues on your own.
