### ISSUE TITLE
TECA compile Error

### ISSUE THREAD

**Issue by bedassa** [LBL-EESA/TECA#411]
[ 97%] Performing build step for 'TECA'
Scanning dependencies of target teca_core
[  1%] [  3%] [  3%] [  3%] [  3%] Building CXX object core/CMakeFiles/teca_core.dir/teca_algorithm.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_algorithm_executive.cxx.o
[  4%] Building CXX object core/CMakeFiles/teca_core.dir/teca_dataset.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_binary_stream.cxx.o
[  5%] [  5%] [  6%] [  7%] Building CXX object core/CMakeFiles/teca_core.dir/teca_index_executive.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_memory_profiler.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_index_reduce.cxx.o
[  7%] Building CXX object core/CMakeFiles/teca_core.dir/teca_metadata.cxx.o
[  8%] [  9%] Building CXX object core/CMakeFiles/teca_core.dir/teca_mpi_manager.cxx.o
[  9%] Building CXX object core/CMakeFiles/teca_core.dir/teca_parallel_id.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_threaded_algorithm.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_profiler.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_thread_pool.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_variant_array.cxx.o
Linking CXX shared library ../lib/libteca_core.so
[ 12%] Built target teca_core
Scanning dependencies of target teca_system
Scanning dependencies of target teca_test_amr
Scanning dependencies of target teca_test_array
Scanning dependencies of target teca_data
[ 12%] [ 12%] Building CXX object system/CMakeFiles/teca_system.dir/teca_system_interface.cxx.o
Building CXX object test/test_amr/CMakeFiles/teca_test_amr.dir/test_amr_metadata.cpp.o
[ 13%] [ 14%] [ 14%] [ 15%] [ 16%] [ 17%] [ 18%] [ 18%] [ 18%] [ 19%] [ 20%] [ 21%] [ 22%] [ 22%] [ 23%] [ 24%] Building CXX object data/CMakeFiles/teca_data.dir/teca_array_collection.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_cartesian_mesh.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_coordinate_util.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_mesh.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_add.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_table_collection.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_executive.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_scalar_multiply.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_uniform_cartesian_mesh.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_source.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_database.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_table.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_temporal_stats.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_writer.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_time_average.cxx.o
Linking CXX shared library ../lib/libteca_system.so
[ 24%] Built target teca_system
Scanning dependencies of target test_mpi_error_handler
Scanning dependencies of target test_stack_trace_signal_handler
[ 25%] [ 26%] /home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/data/teca_coordinate_util.cxx: In function 'int teca_coordinate_util::time_to_string(double, const string&, const string&, const string&, std::string&)':
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/data/teca_coordinate_util.cxx:73:27: warning: missing initializer for member 'tm::tm_sec' [-Wmissing-field-initializers]
     struct tm timedata = {};
                           ^
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/data/teca_coordinate_util.cxx:73:27: warning: missing initializer for member 'tm::tm_min' [-Wmissing-field-initializers]
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/data/teca_coordinate_util.cxx:73:27: warning: missing initializer for member 'tm::tm_hour' [-Wmissing-field-initializers]
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/data/teca_coordinate_util.cxx:73:27: warning: missing initializer for member 'tm::tm_mday' [-Wmissing-field-initializers]
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/data/teca_coordinate_util.cxx:73:27: warning: missing initializer for member 'tm::tm_mon' [-Wmissing-field-initializers]
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/data/teca_coordinate_util.cxx:73:27: warning: missing initializer for member 'tm::tm_year' [-Wmissing-field-initializers]
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/data/teca_coordinate_util.cxx:73:27: warning: missing initializer for member 'tm::tm_wday' [-Wmissing-field-initializers]
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/data/teca_coordinate_util.cxx:73:27: warning: missing initializer for member 'tm::tm_yday' [-Wmissing-field-initializers]
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/data/teca_coordinate_util.cxx:73:27: warning: missing initializer for member 'tm::tm_isdst' [-Wmissing-field-initializers]
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/data/teca_coordinate_util.cxx:73:27: warning: missing initializer for member 'tm::tm_gmtoff' [-Wmissing-field-initializers]
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/data/teca_coordinate_util.cxx:73:27: warning: missing initializer for member 'tm::tm_zone' [-Wmissing-field-initializers]
Building CXX object test/CMakeFiles/test_mpi_error_handler.dir/test_mpi_error_handler.cpp.o
Building CXX object test/CMakeFiles/test_stack_trace_signal_handler.dir/test_stack_trace_signal_handler.cpp.o
Linking CXX executable ../bin/test/test_mpi_error_handler
Linking CXX executable ../bin/test/test_stack_trace_signal_handler
Linking CXX executable ../../bin/test/teca_test_amr
[ 26%] Built target test_stack_trace_signal_handler
[ 26%] Built target teca_test_amr
[ 26%] Built target test_mpi_error_handler
Linking CXX shared library ../lib/libteca_data.so
Linking CXX shared library ../../lib/libteca_test_array.so
[ 26%] Built target teca_test_array
[ 26%] Built target teca_data
Scanning dependencies of target teca_io
[ 26%] [ 27%] [ 28%] Building CXX object io/CMakeFiles/teca_io.dir/teca_file_util.cxx.o
[ 29%] [ 29%] Building CXX object io/CMakeFiles/teca_io.dir/teca_cartesian_mesh_writer.cxx.o
[ 30%] Building CXX object io/CMakeFiles/teca_io.dir/teca_cartesian_mesh_reader.cxx.o
[ 31%] [ 31%] Building CXX object io/CMakeFiles/teca_io.dir/teca_table_reader.cxx.o
[ 32%] Building CXX object io/CMakeFiles/teca_io.dir/teca_table_writer.cxx.o
Building CXX object io/CMakeFiles/teca_io.dir/teca_vtk_util.cxx.o
Building CXX object io/CMakeFiles/teca_io.dir/teca_netcdf_util.cxx.o
Building CXX object io/CMakeFiles/teca_io.dir/teca_cf_writer.cxx.o
Building CXX object io/CMakeFiles/teca_io.dir/teca_cf_reader.cxx.o
Scanning dependencies of target test_pipeline_time_average
Scanning dependencies of target test_pipeline_branches
Scanning dependencies of target test_pipeline_index_reduce
[ 33%] [ 34%] [ 34%] Building CXX object test/CMakeFiles/test_pipeline_time_average.dir/test_pipeline_time_average.cpp.o
Building CXX object test/CMakeFiles/test_pipeline_branches.dir/test_pipeline_branches.cpp.o
Building CXX object test/CMakeFiles/test_pipeline_index_reduce.dir/test_pipeline_index_reduce.cpp.o
Linking CXX executable ../bin/test/test_pipeline_time_average
Linking CXX executable ../bin/test/test_pipeline_branches
[ 34%] Built target test_pipeline_time_average
[ 34%] Built target test_pipeline_branches
Linking CXX executable ../bin/test/test_pipeline_index_reduce
[ 34%] Built target test_pipeline_index_reduce
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/io/teca_cf_reader.cxx: In member function 'virtual teca_metadata teca_cf_reader::get_output_metadata(unsigned int, const std::vector<teca_metadata, std::allocator<teca_metadata> >&)':
/home/bcheneka/Build_WRF/LIBRARIES/TECA_superbuild/build/TECA-prefix/src/TECA/io/teca_cf_reader.cxx:853:27: error: 'get_time' is not a member of 'std'
                     ss >> std::get_time(&current_tm,
                           ^
make[5]: *** [io/CMakeFiles/teca_io.dir/teca_cf_reader.cxx.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [io/CMakeFiles/teca_io.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [TECA-prefix/src/TECA-stamp/TECA-build] Error 2
make[1]: *** [CMakeFiles/TECA.dir/all] Error 2
make: *** [all] Error 2

**Comment by elbashandy** [comment]
`get_time` is a member of `std` since C++11. Try updating your C++ compiler if it's not C++11 or above

**Comment by burlen** [comment]
yup. I think that is the issue too.
