### ISSUE TITLE
new tag for TECA BARD v1.0.1

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#412]
We need a TECA BARD tag for the version number corresponding to what we use in the revised GMD paper: `TECA-BARD-v1.0.1`

@burlen - would you mind doing this?  I'm working on finalizing the GMD paper for resubmission: hopefully in the next day or so.

**Comment by burlen** [comment]
The last tag was called `TECA-BARD-v1.0`. Can we call this one `TECA-BARD-v1.1`?
Should we re-name both of these tags from `TECA` to `CASCADE`?

**Comment by taobrienlbl** [comment]
Can we please go with 1.0.1?  This is for consistency with the paper, and I'm using 1.0.1 instead of 1.1 in the paper to indicate that this is a minor change in the BARD application relative to 1.0.

An I'd prefer to keep the tag name as 'TECA': again for consistency.

**Comment by taobrienlbl** [comment]
I should add that I do recall that we agreed on the versioning convention that you state for TECA releases; I still agree with that.  This is distinct in that it is a tag to help us concisely indicate which commit was used for the BARD paper.

**Comment by burlen** [comment]
OK

**Comment by burlen** [comment]
In that case I'll add a zero to the first tag name.

Should be all set now.
```
$git tag -l
1.9.0
2.0.0
2.1.0
2.1.1
2.1.2
2.1.3
2.2.0
2.2.1
2.2.2
3.0.0
TECA-BARD-v1.0.0
TECA-BARD-v1.0.1
```

**Comment by taobrienlbl** [comment]
perfect: thank you!
