### ISSUE TITLE
pytorch MPI performance

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#415]
The deeplab ar detector has abysmal performance when run with MPI. This is because of the incorrect massive over subscription of threads by pytorch. When setting to 1 thread the performance is also abysmal and is not viable. We need to expose and use our thread management codes to get the number of cores per MPI rank and forward this information to pytorch. We need to document how to run the pytrroch related codes w/ MPI.

**Comment by elbashandy** [comment]
When you say "When setting to 1 thread the performance is also abysmal and is not viable", do you mean setting pytorch threads to 1 or do you mean using `mpiexec -n 1`?

**Comment by burlen** [comment]
#417 resolved the technical issue, but documentation remains to be completed

**Comment by burlen** [comment]
resolved by #529
