### ISSUE TITLE
Build TECA Error

### ISSUE THREAD

**Issue by bedassa** [LBL-EESA/TECA#419]
[ 98%] Performing build step for 'TECA'
Scanning dependencies of target teca_core
[  1%] [  1%] [  2%] [  3%] [  3%] Building CXX object core/CMakeFiles/teca_core.dir/teca_binary_stream.cxx.o
[  4%] [  5%] Building CXX object core/CMakeFiles/teca_core.dir/teca_algorithm.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_algorithm_executive.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_index_executive.cxx.o
[  6%] [  6%] [  7%] [  7%] Building CXX object core/CMakeFiles/teca_core.dir/teca_dataset.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_index_reduce.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_memory_profiler.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_metadata.cxx.o
[  8%] Building CXX object core/CMakeFiles/teca_core.dir/teca_parallel_id.cxx.o
[  9%] [  9%] Building CXX object core/CMakeFiles/teca_core.dir/teca_mpi_manager.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_threaded_algorithm.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_thread_pool.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_profiler.cxx.o
Building CXX object core/CMakeFiles/teca_core.dir/teca_variant_array.cxx.o
Linking CXX shared library ../lib/libteca_core.so
[ 12%] Built target teca_core
Scanning dependencies of target teca_system
Scanning dependencies of target teca_test_amr
[ 12%] Scanning dependencies of target teca_data
Building CXX object system/CMakeFiles/teca_system.dir/teca_system_interface.cxx.o
Scanning dependencies of target teca_test_array
[ 12%] Building CXX object test/test_amr/CMakeFiles/teca_test_amr.dir/test_amr_metadata.cpp.o
[ 13%] [ 13%] [ 14%] [ 16%] [ 17%] [ 17%] [ 18%] [ 18%] [ 18%] [ 20%] [ 20%] [ 21%] [ 22%] [ 22%] [ 23%] [ 24%] Building CXX object data/CMakeFiles/teca_data.dir/teca_array_collection.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_mesh.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_coordinate_util.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_cartesian_mesh.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_table.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_add.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_scalar_multiply.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_table_collection.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_uniform_cartesian_mesh.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_temporal_stats.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_executive.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_source.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_writer.cxx.o
Building CXX object data/CMakeFiles/teca_data.dir/teca_database.cxx.o
Building CXX object test/test_array/CMakeFiles/teca_test_array.dir/array_time_average.cxx.o
Linking CXX shared library ../lib/libteca_system.so
[ 24%] Built target teca_system
Scanning dependencies of target test_mpi_error_handler
Scanning dependencies of target test_stack_trace_signal_handler
[ 26%] [ 26%] Building CXX object test/CMakeFiles/test_stack_trace_signal_handler.dir/test_stack_trace_signal_handler.cpp.o
Building CXX object test/CMakeFiles/test_mpi_error_handler.dir/test_mpi_error_handler.cpp.o
Linking CXX executable ../bin/test/test_mpi_error_handler
Linking CXX executable ../bin/test/test_stack_trace_signal_handler
../lib/libteca_core.so: undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'
../lib/libteca_core.so: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libteca_core.so: undefined reference to `boost::program_options::arg[abi:cxx11]'
../lib/libteca_core.so: undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
../lib/libteca_core.so: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../lib/libteca_core.so: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
../lib/libteca_core.so: undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../lib/libteca_core.so: undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
collect2: error: ld returned 1 exit status
make[5]: *** [bin/test/test_mpi_error_handler] Error 1
make[4]: *** [test/CMakeFiles/test_mpi_error_handler.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
../lib/libteca_core.so: undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'
../lib/libteca_core.so: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libteca_core.so: undefined reference to `boost::program_options::arg[abi:cxx11]'
../lib/libteca_core.so: undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
../lib/libteca_core.so: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../lib/libteca_core.so: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
../lib/libteca_core.so: undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../lib/libteca_core.so: undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
collect2: error: ld returned 1 exit status
make[5]: *** [bin/test/test_stack_trace_signal_handler] Error 1
make[4]: *** [test/CMakeFiles/test_stack_trace_signal_handler.dir/all] Error 2
Linking CXX executable ../../bin/test/teca_test_amr
../../lib/libteca_core.so: undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'
../../lib/libteca_core.so: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../lib/libteca_core.so: undefined reference to `boost::program_options::arg[abi:cxx11]'
../../lib/libteca_core.so: undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
../../lib/libteca_core.so: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../../lib/libteca_core.so: undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
../../lib/libteca_core.so: undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../../lib/libteca_core.so: undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const'
collect2: error: ld returned 1 exit status
make[5]: *** [bin/test/teca_test_amr] Error 1
make[4]: *** [test/test_amr/CMakeFiles/teca_test_amr.dir/all] Error 2
Linking CXX shared library ../../lib/libteca_test_array.so
[ 26%] Built target teca_test_array
Linking CXX shared library ../lib/libteca_data.so
[ 26%] Built target teca_data
make[3]: *** [all] Error 2
make[2]: *** [TECA-prefix/src/TECA-stamp/TECA-build] Error 2
make[1]: *** [CMakeFiles/TECA.dir/all] Error 2
make: *** [all] Error 2

**Comment by burlen** [comment]
I want to help, but there's not enough information here. I assume you've upgraded the compilers now? which ones are you using? Is this a cluster or a Cray system?

One issue with the superbuild is that when it errors out one must `rm -rf *` both the build and install directories. Not doing so can cause odd errors, it's priobably not the issue here, but thought I'd mention since you're obviously having to run it multiple times.

**Comment by burlen** [comment]
we don't have any actionable information here, the question is do we need to test on more platforms? if so which ones? It would help to have information about what platform the issue occurred. we may help the user provide this with an issue template
