### ISSUE TITLE
investigate an alternative to metadata cache files

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#443]
for instance:
* placing them in some shared/common location that's out of sight
* using MPI parallelism to parse the time axis

**Comment by taobrienlbl** [comment]
Following the conversation in #435 -- for the time being, we are doing quite a bit of TECA development; the md hash changes with each commit right (or is it with the release)?  If it is changing rapidly, then there's not much benefit if the cache files quickly go obsolete during our development process.

**Comment by burlen** [comment]
as far as placing the cache file in the data directory, the cache optimization is really intended for large production runs on cori by the users. these runs would presumably be made from an official release, and would be stable for some period. 6 mos - 1 year given our current rate of releases?  for instance a user on cori would access teca from the official install via a module load teca and get the same version.

But the cache optimization also helps with large development runs on cori - at least for my work flow. My work flow is based on first running the teca_metadata_probe on the dataset to see what's there given the regex that I think will work. this is done on the login node from one process. running the teca_metadata_probe creates the cache file. I use the output of the metadata_probe to debug the regex and aid in writing my batch script, for instance to get the number of nodes -N and processes -n correct. in the batch job run where I process 10's of thousands of time steps on as many cores, the cache file generated by the metadata probe is used and is providing some substantial reduction resource use. this use case would also work if the cache file were found in any path.

**Comment by burlen** [comment]
for the cf_reader this was resolved by #506 which implemented the MPI solution and disabled the md files. Will need to prot this to the wrf reader.
