### ISSUE TITLE
Setup doxygen and display it in read the docs

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#478]
set up doxygen and display it on read the docs. there will be some configuration needed to tell doxygen to parse our code. We probably will need to make a pass over the headers to add more mark up, but the idea here is just to get something on the screen.
See also: https://www.doxygen.nl/index.html

the breathe project seems to a good starting point for displaying in rtd. if it turns out that there are major issues with breathe we can evaluate other options.
See also https://breathe.readthedocs.io/en/latest/

**Comment by elbashandy** [comment]
Creating a list of files that need to conform to Doxygen's documentation style:

Algorithms:

- [ ] teca_2d_component_area
- [ ] teca_apply_binary_mask
- [ ] teca_ar_detect
- [ ] teca_bayesian_ar_detect
- [ ] teca_bayesian_ar_detect_parameters
- [ ] teca_binary_segmentation
- [ ] teca_cartesian_mesh_regrid
- [ ] teca_cartesian_mesh_source
- [ ] teca_cartesian_mesh_subset
- [ ] teca_component_area_filter
- [ ] teca_component_statistics
- [ ] teca_connected_components
- [ ] teca_dataset_capture
- [ ] teca_dataset_diff
- [ ] teca_dataset_source
- [ ] teca_deeplab_ar_detect
- [ ] teca_derived_quantity
- [ ] teca_derived_quantity_numerics
- [ ] teca_descriptive_statistics
- [ ] teca_distance_function
- [ ] teca_evaluate_expression
- [ ] teca_face_to_cell_centering
- [ ] teca_geography
- [ ] teca_geometry
- [ ] teca_integrated_vapor_transport
- [ ] teca_l2_norm
- [ ] teca_laplacian
- [ ] teca_latitude_damper
- [ ] teca_mask
- [ ] teca_model_segmentation
- [ ] teca_normalize_coordinates
- [ ] teca_parser
- [ ] teca_python_algorithm
- [ ] teca_python_reduce
- [ ] teca_saffir_simpson
- [ ] teca_table_calendar
- [ ] teca_table_reduce
- [ ] teca_table_region_mask
- [ ] teca_table_remove_rows
- [ ] teca_table_sort
- [ ] teca_table_to_stream
- [ ] teca_tc_activity
- [ ] teca_tc_candidates
- [ ] teca_tc_classify
- [ ] teca_tc_stats
- [ ] teca_tc_trajectory
- [ ] teca_tc_trajectory_scalars
- [ ] teca_tc_wind_radii
- [ ] teca_tc_wind_radii_stats
- [ ] teca_temporal_average
- [ ] teca_temporal_reduction
- [ ] teca_threaded_python_algorithm
- [ ] teca_variant_array_operand
- [ ] teca_variant_array_operator
- [ ] teca_vertical_coordinate_transform
- [ ] teca_vertical_reduction
- [ ] teca_vorticity

Core:
- [ ] teca_algorithm
- [ ] teca_algorithm_executive
- [ ] teca_algorithm_fwd
- [ ] teca_algorithm_output_port
- [ ] teca_binary_stream
- [ ] teca_calendar
- [ ] teca_common
- [ ] teca_dataset
- [ ] teca_dataset_fwd
- [ ] teca_index_executive
- [ ] teca_index_reduce
- [ ] teca_index_reduce_fwd
- [ ] teca_memory_profiler
- [ ] teca_metadata
- [ ] teca_metadata_util
- [ ] teca_mpi
- [ ] teca_mpi_manager
- [ ] teca_output_port
- [ ] teca_parallel_id
- [ ] teca_profiler
- [ ] teca_program_options
- [ ] teca_programmable_algorithm
- [ ] teca_programmable_algorithm_fwd
- [ ] teca_programmable_reduce
- [ ] teca_programmable_reduce_fwd
- [ ] teca_shared_object
- [ ] teca_string_util
- [ ] teca_system_util
- [ ] teca_thread_pool
- [ ] teca_thread_util
- [ ] teca_threaded_algorithm
- [ ] teca_threaded_algorithm_fwd
- [ ] teca_threaded_programmable_algorithm
- [ ] teca_threadsafe_queue
- [ ] teca_type_select
- [ ] teca_uuid
- [ ] teca_variant_array
- [ ] teca_variant_array_fwd

Data

- [ ] teca_arakawa_c_grid
- [ ] teca_array_attributes
- [ ] teca_array_collection
- [ ] teca_array_collection_fwd
- [ ] teca_cartesian_mesh
- [ ] teca_coordinate_util
- [ ] teca_curvilinear_mesh
- [ ] teca_database
- [ ] teca_database_fwd
- [ ] teca_dataset_util
- [ ] teca_mesh
- [ ] teca_mesh_fwd
- [ ] teca_table
- [ ] teca_table_collection
- [ ] teca_table_collection_fwd
- [ ] teca_table_fwd
- [ ] teca_uniform_cartesian_mesh
- [ ] teca_uniform_cartesian_mesh_fwd

I/O

- [ ] teca_cartesian_mesh_reader
- [ ] teca_cartesian_mesh_reader_factory
- [ ] teca_cartesian_mesh_writer
- [ ] teca_cartesian_mesh_writer_factory
- [ ] teca_cf_layout_manager
- [ ] teca_cf_reader
- [ ] teca_cf_time_step_mapper
- [ ] teca_cf_writer
- [ ] teca_file_util
- [ ] teca_multi_cf_reader
- [ ] teca_netcdf_util
- [ ] teca_table_reader
- [ ] teca_table_writer
- [ ] teca_vtk_util
- [ ] teca_wrf_reader

**Comment by burlen** [comment]
done. thanks @elbashandy
