### ISSUE TITLE
Missing value handling in IVT integral

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#504]
For testing the missing value handling, here is a path to a HighResMIP run with missing values in the lower levels:

/global/cfs/cdirs/m3522/cmip6/CMIP6_hrmcol/HighResMIP/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i2p1f1/E3hrPt

(e.g., see /global/cfs/cdirs/m3522/cmip6/CMIP6_hrmcol/HighResMIP/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i2p1f1/E3hrPt/hus/gn/v20180605/hus_E3hrPt_HadGEM3-GC31-HM_highresSST-present_r1i2p1f1_gn_195001010300-195001302100.nc )

**Comment by taobrienlbl** [comment]
sea level pressure is in this directory `/global/cfs/cdirs/m3522/cmip6/CMIP6_hrmcol/HighResMIP/CMIP6/HighResMIP/MOHC/HadGEM3-GC31-HM/highresSST-present/r1i2p1f1/E3hr/psl/gn/v20180605` for this particular run

**Comment by burlen** [comment]
resolved by #520
