### ISSUE TITLE
Error in installing with -DBUILD_TESTING=ON flag

### ISSUE THREAD

**Issue by venugopalrt** [LBL-EESA/TECA#555]
Following error occured while installing TECA on desktop. Both TECA and TECA_data were downloaded into home directory and running the cmake in /home/user/TECA/bin

CMake Error at CMakeLists.txt:350 (message):
  TECA_data -- required but not found

**Comment by burlen** [comment]
Assuming that you've checked out the TECA_data repo into `/home/user/TECA_data`, please add the flag
```
-DTECA_DATA_ROOT=/home/user/TECA_data
```
to the cmake invocation. Passing the path to the test data repo should solve this issue.

**Comment by venugopalrt** [comment]
> Assuming that you've checked out the TECA_data repo into `/home/user/TECA_data`, please add the flag
> 
> ```
> -DTECA_DATA_ROOT=/home/user/TECA_data
> ```
> 
> to the cmake invocation. Passing the path to the test data repo should solve this issue.

Thank you Burlen. It did solve the issue.
