### ISSUE TITLE
multi_cf_reader fails if MCF contains mixture of 2D and 3D files

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#589]
When using the multi_cf_reader, an error occurs if the main file has a given geometry (e.g., it is 4D: time, plev, lat, lon), but one of th CF reader groups contains 3D-only variables (e.g., time, lat, lon).

The use-case here is calculating AR-weighted precipitation, when using `teca_bayesian_ar_detect` to calculate integrals.  I'm using this on the C20C data, and this will be an issue for the HighResMIP runs as well, since we'll want to calculate AR-weighted precipitation there too.

This occurs because `teca_multi_cf_reader.cxx` passes `this->z_axis_variable` to each reader within the group ([line 654 of io/teca_multi_cf_reader.cxx](https://github.com/LBL-EESA/TECA/blob/a0fc3f68f206c69b7dfa50a2e25e9da7fd56cb15/io/teca_multi_cf_reader.cxx#L654)).

One way around this would be to add a capability to set `z_axis_variable` for a specific CF reader group in the MCF file, e.g.:

```
[cf_reader]
variables = pr
z_axis_variable = ""
regex = %data_root%/pr/{run}/pr_%regex%
```

The command I'm attempting to run on 20 KNL nodes follows:
```bash
# load gcc
module swap PrgEnv-intel PrgEnv-gnu

# bring a TECA install into your environment.
module use /global/common/software/m1517/teca/develop/modulefiles/
module load teca

# print the commands as the execute, and error out if any one command fails
set -e
set -x

#*******************************************************************************
#*******************************************************************************
#* windhusavi_A3hr_CAM5-1-1degree_All-Hist_est1_v2-0_run002_%t%.nc 
#*******************************************************************************
#*******************************************************************************
# make a directory for the output files
mkdir -p C20C_BARD_outputs_v2/LBNL/CAM5-1-1degree/All-Hist/est1/v2-0/3hr/atmos/windhusavi/run002/

srun -N 20 -n 340 -c 16 --cpu_bind=cores \
    teca_bayesian_ar_detect \
        --input_file mcf_files_v2/All-Hist_est1_v2-0_run002.mcf \
        --specific_humidity hus --wind_u ua --wind_v va \
        --ivt_u uhusavi --ivt_v vhusavi --ivt windhusavi \
        --compute_ivt --write_ivt --write_ivt_magnitude --steps_per_file 2920 \
        --ar_weighted_variables pr \
        --output_file C20C_BARD_outputs_v2/LBNL/CAM5-1-1degree/All-Hist/est1/v2-0/3hr/atmos/windhusavi/run002//windhusavi_A3hr_CAM5-1-1degree_All-Hist_est1_v2-0_run002_%t%.nc 
```

Here are the contents of the associated MCF file:

`mcf_files_v2/All-Hist_est1_v2-0_run002.mcf`
```
# TECA multi cf reader config

data_root = /global/cscratch1/sd/taobrien/C20C_ua_va_hus/LBNL/CAM5-1-1degree/All-Hist/est1/v2-0/3hr/atmos/
regex = A3hr_CAM5-1-1degree_All-Hist_est1_v2-0.*\.nc$

[cf_reader]
variables = hus
regex = %data_root%/hus/run002/hus_%regex%
provides_time
provides_geometry

[cf_reader]
variables = ua
regex = %data_root%/ua/run002/ua_%regex%

[cf_reader]
variables = va
regex = %data_root%/va/run002/va_%regex%

[cf_reader]
variables = pr
regex = %data_root%/pr/run002/pr_%regex%
```

The files referred to in the MCF file should be group-readable by m1517 users.

**Comment by burlen** [comment]
The per reader controls would certainly be useful. The cf reader might be modified to make this work without the per reader controls. Either way we will need to enable 2d and 3d arrays in the same mesh object, and likely make some revisions to the cf_writer. The WRF reader and Arakawa C grid have these features already.
