### ISSUE TITLE
need a way to remove singleton dimensions

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#591]
@burlen -- not sure if we want to include it in this PR or not, but I just came across another complicating factor that appears in some datasets: 2D variables having a 1-element Z dimension.

For the C20C case that I'm attempting to analyze, the precipitation variable has a 'height' dimension.  This dimension is actually meaningless and should be ignored, since only one height can be selected.  See the variable 'pr' below for an example.

```
teca_metadata_probe --input_file test.mcf 

A total of 248 steps available. Using the 365_day calendar. Times are specified
in units of days since 2014-10-01 00:00:00. The available times range from
2016-1-1 1:30:0 (457.062) to 2016-1-31 22:30:0 (487.938).

Mesh dimension: 2D
Mesh coordinates: lon, lat
Mesh extents: 0, 287, 0, 191
Mesh bounds: 0, 358.75, -90, 90

9 data arrays available

  Id   Name              Type        Dimensions                  Shape                 
--------------------------------------------------------------------------------
  1    ar_binary_tag     NC_BYTE     [time, lat, lon]            [248, 192, 288]       
  2    ar_probability    NC_FLOAT    [time, lat, lon]            [248, 192, 288]       
  3    lat               NC_FLOAT    [lat]                       [192]                 
  4    lon               NC_FLOAT    [lon]                       [288]                 
  5    pr                NC_FLOAT    [time, height, lat, lon]    [248, 1, 192, 288]    
  6    time              NC_FLOAT    [time]                      [248]                 
  7    uhusavi           NC_FLOAT    [time, lat, lon]            [248, 192, 288]       
  8    vhusavi           NC_FLOAT    [time, lat, lon]            [248, 192, 288]       
  9    windhusavi        NC_FLOAT    [time, lat, lon]            [248, 192, 288]       
```

It is unfortunately not rare for models to output not-really-3D variables like this.  This is most common for 2m temperature and wind, where a height variable is often given that indicates the height of the modeled measurement (i.e., height = 2 m).  Some datasets will have this mixed in with the real 3D data, so from TECA's point of view it might appear that there are two sets of 3D variables in the same dataset: the real 3D data and these 2D variables with a fake height dimension.

_Originally posted by @taobrienlbl in https://github.com/LBL-EESA/TECA/issues/590#issuecomment-811280408_

**Comment by burlen** [comment]
Yes, I noticed that too. #590 will solve this (not quite ready for you yet). You'll need to specify  "z_axis_variable = height" in the MCF reader section for that reader only. Will provide more info on the new MCF file features when it's finalized

By the way the teca_cf_restripe app removes vertical dimension if it's only 1 in length.

**Comment by taobrienlbl** [comment]
okay, good to know that #590 will fix this--I'll hold on pushing forward for now.  And thanks for letting me know that `teca_cf_restripe` would do that.

**Comment by taobrienlbl** [comment]
Verified that #590 fixes this for the specific use case that raised the issue. Thanks for this @burlen!
