### ISSUE TITLE
teca_cf_restripe is not in RTD

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#592]
The `teca_cf_restripe` app (`TECA/apps/teca_cf_restripe.cpp`) is now part of the TECA app suite, but it is not yet documented in read-the-docs.  It should appear in the [table of TECA apps](https://teca.readthedocs.io/en/latest/applications.html#command-line-applications), and it should have a dedicated section (like https://teca.readthedocs.io/en/latest/applications.html#teca-bayesian-ar-detect).

It would be good to verify that there are no other yet-un-documented apps when doing this.

@burlen - if you think we should keep this app out of the docs for now, please let us know, and we'll hold off on this issue.

**Comment by taobrienlbl** [comment]
A potential benefit of getting the documentation in before that could be that it allows you to focus on documenting the new features and the new example, whereas @elbashandy could focus on getting up on RTD and documenting the existing command line options.  This would also make the restripe app visible sooner, which could be good since it has some useful features.

I don't have strong feelings either way though.

**Comment by burlen** [comment]
I don't have strong feeling either way, just wanted you guys to know that this one is a moving target and would likely need to have an major overhaul in the near term anyway.
