### ISSUE TITLE
clean up and merge the Breathe example

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#594]
#505 illustrates Breathe working. This functionality will be used in the catalogue of algorithms and data model documentation that in in progress. Please put the just the changes that illustrate Breathe into a new PR for review.

**Comment by elbashandy** [comment]
@burlen can you elaborate more on why we need Breathe to be integrated? I haven't settled on the approach on how we are going to add the cataloging feature we are going to add. So far I am not leaning towards Breathe unless it's obviously the best solution.

**Comment by burlen** [comment]
I am going to use Breathe as I write documentation, which has no connection to what you've been working on or will work on. You're work on getting Breathe going is very helpful and we don't want to loose it.

**Comment by burlen** [comment]
resolved in #596
