### ISSUE TITLE
python exceptions aren't raised after #645

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#648]
Both @indahector and I are developing python-based TECA pipelines and have found that information about Python's exceptions is no longer printed as of #645 .  We have both been using the stable build at NERSC while debugging.

Is there some sort of runtime configuration that print Python exception information?

**Comment by burlen** [comment]
@taobrienlbl is it the case that your code now aborts with the error message immediately but you expected an exception to be raised instead?

**Comment by burlen** [comment]
@taobrienlbl  The stable install pre-dates #645. #645 is only in the develop install. 

The mpi4py Python exception handler, which leads to deadlocks, and can waste large amounts of our compute budget, was why #645 was finally done. In the latest develop installs Python code should abort immediately.

**Comment by taobrienlbl** [comment]
>is it the case that your code now aborts with the error message immediately but you expected an exception to be raised instead?
that's correct.  

> The stable install pre-dates #645. #645 is only in the develop install.
To be clear, we originally started working on develop (post #645) and reverted to stable when we realized that we couldn't get information about exceptions in our user-generated code.

**Comment by taobrienlbl** [comment]
This is fixed by #650
