### ISSUE TITLE
lapse rate tests not running in cpu build

### ISSUE THREAD

**Issue by burlen** [LBL-EESA/TECA#716]
The cmake code for the lapse rate test requires CUDA and cupy. However this class should run fine without those dependencies. remove the requirement so that the test runs in CPU only build

**Comment by amandasd** [comment]
Hi @burlen. Should I create a new branch to solve this issue?

**Comment by burlen** [comment]
sounds good

**Comment by burlen** [comment]
does the test read data from or write data to a netcdf file?

**Comment by amandasd** [comment]
The input and output files are netcdf files.
