### ISSUE TITLE
implement connected component for GPU

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#754]
The connected component algorithm is currently only implemented for the CPU.  A GPU implementation is required for, e.g., running TECA BARD fully on the GPU.

This should hopefully be straightforward, since a few recent papers describe GPU implementations in detail, and several CUDA implementations exist on github and other sources:

* [slides from NVIDIA describing the HA64 GPU CC algorithm](https://developer.download.nvidia.com/video/gputechconf/gtc/2019/presentation/s9111-a-new-direct-connected-component-labeling-and-analysis-algorithm-for-gpus.pdf)
    * [the associated paper](https://hal.science/hal-01923784/file/dasip2018_final.pdf)
* [another parallel CC algorithm](https://hal.science/hal-01923784/file/dasip2018_final.pdf)
* [the ECL CC algorithm](https://userweb.cs.txstate.edu/~burtscher/research/ECL-CC/)
    * [w/ it's associated code](https://userweb.cs.txstate.edu/~burtscher/research/ECL-CC/)
* [a survey of a lot of GPU CC algorithms](https://dl.acm.org/doi/pdf/10.1145/3410463.3414657)
* [an old CC CUDA implementation](https://github.com/ironhide23586/CUDA-Connected-Component-Labelling)
* [a pytorch CC implementation w/ CUDA kernels (BSD)](https://github.com/zsef123/Connected_components_PyTorch)
* [a graph-based CC implementation for both openmp and cuda](https://github.com/michaelsutton/afforest)
*

**Comment by burlen** [comment]
I have been working with the HA64 algorithm

**Comment by taobrienlbl** [comment]
oh cool, didn't realize!
