### ISSUE TITLE
TECA BARD does not default to periodic_in_x=1 even though the documentation indicates it should

### ISSUE THREAD

**Issue by taobrienlbl** [LBL-EESA/TECA#792]
The help for `teca_bayesian_ar_detect --help` indicates the following:

```
  --periodic_in_x arg (=1)
    
    Flags whether the x dimension (typically longitude) is periodic.
```

This suggests that by default, TECA BARD should assume that datasets are periodic, which is consistent with the underlying assumption in BARD that the data are global.  The actual default value is zero because [`teca_bayesian_ar_detect.cxx`](https://github.com/LBL-EESA/TECA/blob/b77e030197f9ca417cc920aa91ee96e921cbeb41/apps/teca_bayesian_ar_detect.cpp#L343) defers setting the mesh periodicity if the default value is provided on the command line; this delegates selection of the default value to the CF reader, which has a default of 0.

Datasets produced with TECA BARD that did not explicitly set the `--periodic_in_x` flag will therefore not treat ARs crossing the periodic boundary correctly.

**Comment by burlen** [comment]
This bug only occurs when the MCF reader is used. The ar detect app does force periodic boundary for the CF reader
https://github.com/LBL-EESA/TECA/blob/b77e030197f9ca417cc920aa91ee96e921cbeb41/apps/teca_bayesian_ar_detect.cpp#L183
the app should also do the same for the MCF reader (this would occur around line 187) .
